---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    environment: shared
---
apiVersion: v1
kind: Namespace
metadata:
  name: registry
  labels:
    name: registry
    environment: shared
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx
    environment: shared
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
    environment: shared
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    name: vault
    environment: shared