---
# Titre: Validation post-déploiement pour Keycloak
# Description: Valide le déploiement de Keycloak
# Auteur: Équipe LIONS Infrastructure
# Date: 2025-05-07
# Version: 1.0.0

- name: Attente que Keycloak soit prêt
  uri:
    url: "http://{{ app_name }}.{{ app_namespace }}.svc.cluster.local:{{ keycloak_default_port }}{{ keycloak_health_path }}/ready"
    status_code: 200
    validate_certs: no
  register: health_check
  until: health_check.status == 200
  retries: 30
  delay: 10
  ignore_errors: yes

- name: Vérification de l'état de santé de Keycloak
  debug:
    msg: "Keycloak {{ app_name }} est en bonne santé et prêt à recevoir des requêtes."
  when: health_check is succeeded

- name: Avertissement si Keycloak n'est pas en bonne santé
  debug:
    msg: "AVERTISSEMENT: Keycloak {{ app_name }} n'est pas en bonne santé. Vérifiez les logs pour plus d'informations."
  when: health_check is failed

- name: Récupération de l'URL d'accès
  set_fact:
    app_url: "https://{{ app_domain }}"
  when: app_environment != 'development' or (extra_params.create_ingress | default(true) | bool)

- name: Affichage de l'URL d'accès
  debug:
    msg: "Keycloak {{ app_name }} est accessible à l'adresse: {{ app_url }}"
  when: app_url is defined

- name: Vérification de l'accessibilité externe (si ingress est configuré)
  uri:
    url: "{{ app_url }}"
    method: GET
    status_code: 200, 301, 302, 307, 308
    validate_certs: no
    follow_redirects: no
  register: external_check
  ignore_errors: yes
  when: app_url is defined

- name: Affichage du résultat de la vérification externe
  debug:
    msg: "Keycloak {{ app_name }} est accessible depuis l'extérieur."
  when: external_check is defined and external_check is succeeded

- name: Avertissement si Keycloak n'est pas accessible depuis l'extérieur
  debug:
    msg: "AVERTISSEMENT: Keycloak {{ app_name }} n'est pas accessible depuis l'extérieur. Vérifiez la configuration de l'ingress."
  when: external_check is defined and external_check is failed

- name: Vérification de l'accès à la console d'administration
  uri:
    url: "http://{{ app_name }}.{{ app_namespace }}.svc.cluster.local:{{ keycloak_default_port }}/auth/admin/"
    status_code: 200, 301, 302, 307, 308
    validate_certs: no
  register: admin_console_check
  ignore_errors: yes

- name: Affichage du résultat de la vérification de la console d'administration
  debug:
    msg: "La console d'administration de Keycloak est accessible."
  when: admin_console_check is succeeded

- name: Avertissement si la console d'administration n'est pas accessible
  debug:
    msg: "AVERTISSEMENT: La console d'administration de Keycloak n'est pas accessible. Vérifiez la configuration."
  when: admin_console_check is failed

- name: Vérification des métriques Prometheus
  uri:
    url: "http://{{ app_name }}.{{ app_namespace }}.svc.cluster.local:{{ keycloak_prometheus_port }}{{ keycloak_prometheus_path }}"
    status_code: 200
    validate_certs: no
  register: metrics_check
  ignore_errors: yes
  when: keycloak_prometheus_scrape | bool

- name: Affichage du résultat de la vérification des métriques
  debug:
    msg: "Les métriques Prometheus sont disponibles pour Keycloak {{ app_name }}."
  when: metrics_check is defined and metrics_check is succeeded

- name: Avertissement si les métriques ne sont pas disponibles
  debug:
    msg: "AVERTISSEMENT: Les métriques Prometheus ne sont pas disponibles pour Keycloak {{ app_name }}."
  when: metrics_check is defined and metrics_check is failed

- name: Vérification de la connexion à la base de données
  uri:
    url: "http://{{ app_name }}.{{ app_namespace }}.svc.cluster.local:{{ keycloak_default_port }}/health/ready"
    status_code: 200
    validate_certs: no
  register: db_check
  ignore_errors: yes

- name: Affichage du résultat de la vérification de la base de données
  debug:
    msg: "La connexion à la base de données est fonctionnelle pour Keycloak {{ app_name }}."
  when: db_check is succeeded

- name: Avertissement si la connexion à la base de données n'est pas fonctionnelle
  debug:
    msg: "AVERTISSEMENT: La connexion à la base de données n'est pas fonctionnelle pour Keycloak {{ app_name }}."
  when: db_check is failed

- name: Enregistrement des informations de déploiement
  copy:
    content: |
      Application: {{ app_name }}
      Version: {{ app_version }}
      Environnement: {{ app_environment }}
      Namespace: {{ app_namespace }}
      URL: {{ app_url | default('Non disponible') }}
      Date de déploiement: {{ ansible_date_time.iso8601 }}
      Statut: {{ 'Succès' if health_check is succeeded else 'Avertissement' }}
      
      Ressources:
        Replicas: {{ app_replicas }}
        CPU Requests: {{ app_resources.requests.cpu }}
        Memory Requests: {{ app_resources.requests.memory }}
        CPU Limits: {{ app_resources.limits.cpu }}
        Memory Limits: {{ app_resources.limits.memory }}
      
      Monitoring:
        Prometheus: {{ 'Activé' if keycloak_prometheus_scrape | bool else 'Désactivé' }}
        Métriques: {{ 'Disponibles' if metrics_check is defined and metrics_check is succeeded else 'Non disponibles' }}
      
      Base de données:
        Connexion: {{ 'Fonctionnelle' if db_check is succeeded else 'Non fonctionnelle' }}
      
      Console d'administration:
        Accès: {{ 'Fonctionnel' if admin_console_check is succeeded else 'Non fonctionnel' }}
      
      Notes:
      - Vérifiez les logs de Keycloak pour plus d'informations.
      - Pour les problèmes, contactez l'équipe d'infrastructure.
    dest: "/var/log/lions/deployments/{{ app_name }}-{{ app_environment }}-{{ ansible_date_time.date }}.log"
    mode: '0644'
  ignore_errors: yes

- name: Nettoyage des fichiers temporaires
  file:
    path: "{{ temp_dir.path }}"
    state: absent
  changed_when: false
  ignore_errors: yes