---
# =========================================================================
# LIONS INFRASTRUCTURE 5.0 - RÔLE PGADMIN
# =========================================================================
# Description: Orchestrateur principal pour le déploiement pgAdmin
# Version: 5.0.0
# Maintainer: DevOps Team <devops@lions.dev>
# Documentation: https://docs.lions.dev/infrastructure/services/pgadmin
# =========================================================================

# =========================================================================
# MÉTADONNÉES ET CONFIGURATION
# =========================================================================
- name: "pgAdmin | Initialisation des métadonnées de déploiement"
  set_fact:
    pgadmin_deployment_metadata:
      role_name: "pgadmin"
      role_version: "5.0.0"
      deployment_id: "{{ ansible_date_time.epoch }}"
      environment: "{{ lions_environment | default('development') }}"
      namespace: "{{ lions_pgadmin_namespace | default('database-tools') }}"
      started_at: "{{ ansible_date_time.iso8601 }}"
      started_by: "{{ ansible_user_id | default('system') }}"
    pgadmin_deployment_config:
      dry_run: "{{ lions_dry_run | default(false) | bool }}"
      debug_mode: "{{ lions_debug_mode | default(false) | bool }}"
      skip_validation: "{{ pgadmin_skip_validation | default(false) | bool }}"
      force_recreate: "{{ pgadmin_force_recreate | default(false) | bool }}"
  tags:
    - pgadmin
    - metadata
    - always

- name: "pgAdmin | Affichage des informations de déploiement"
  debug:
    msg:
      - "🚀 Démarrage du déploiement pgAdmin"
      - "📊 Environnement: {{ pgadmin_deployment_metadata.environment }}"
      - "🏷️  Namespace: {{ pgadmin_deployment_metadata.namespace }}"
      - "🆔 ID de déploiement: {{ pgadmin_deployment_metadata.deployment_id }}"
      - "⏰ Démarré le: {{ pgadmin_deployment_metadata.started_at }}"
      - "👤 Initié par: {{ pgadmin_deployment_metadata.started_by }}"
      - "🔧 Mode debug: {{ pgadmin_deployment_config.debug_mode }}"
      - "🧪 Dry run: {{ pgadmin_deployment_config.dry_run }}"
  when: pgadmin_deployment_config.debug_mode | bool
  tags:
    - pgadmin
    - debug
    - always

# =========================================================================
# GESTION DES ERREURS ET ROLLBACK
# =========================================================================
- name: "pgAdmin | Configuration de la gestion d'erreurs"
  set_fact:
    pgadmin_error_handling:
      max_retries: "{{ pgadmin_max_retries | default(3) }}"
      retry_delay: "{{ pgadmin_retry_delay | default(10) }}"
      rollback_on_failure: "{{ pgadmin_rollback_on_failure | default(true) | bool }}"
      error_log_file: "/tmp/pgadmin-deployment-{{ pgadmin_deployment_metadata.deployment_id }}.log"
  tags:
    - pgadmin
    - error-handling
    - always

# =========================================================================
# VÉRIFICATIONS PRÉALABLES CRITIQUES
# =========================================================================
- name: "pgAdmin | Vérification de l'état de l'environnement"
  block:
    - name: "pgAdmin | Vérification de l'accessibilité du cluster Kubernetes"
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Namespace
        name: "{{ pgadmin_deployment_metadata.namespace }}"
      register: pgadmin_namespace_check
      failed_when: false

    - name: "pgAdmin | Vérification des variables d'environnement critiques"
      assert:
        that:
          - lions_pgadmin_enabled is defined
          - lions_pgadmin_enabled | bool
          - lions_pgadmin_version is defined
          - lions_pgadmin_version | length > 0
          - pgadmin_deployment_metadata.namespace is defined
        fail_msg: "Variables d'environnement pgAdmin manquantes ou incorrectes"
        success_msg: "Variables d'environnement pgAdmin validées"

  rescue:
    - name: "pgAdmin | Gestion d'erreur - Vérifications préalables"
      fail:
        msg: "❌ Échec des vérifications préalables pgAdmin: {{ ansible_failed_result.msg | default('Erreur inconnue') }}"

  tags:
    - pgadmin
    - preflight
    - validation

# =========================================================================
# PHASE 1: PRÉREQUIS ET DÉPENDANCES
# =========================================================================
- name: "pgAdmin | Phase 1 - Vérification des prérequis"
  block:
    - name: "pgAdmin | Inclusion des tâches de prérequis"
      include_tasks: prerequisites.yml
      vars:
        current_phase: "prerequisites"
        phase_description: "Vérification des prérequis système et Kubernetes"

  rescue:
    - name: "pgAdmin | Échec Phase 1 - Prérequis"
      set_fact:
        pgadmin_deployment_failed: true
        pgadmin_failure_phase: "prerequisites"
        pgadmin_failure_reason: "{{ ansible_failed_result.msg | default('Échec des prérequis') }}"

    - name: "pgAdmin | Log d'erreur Phase 1"
      lineinfile:
        path: "{{ pgadmin_error_handling.error_log_file }}"
        line: "[{{ ansible_date_time.iso8601 }}] ERREUR Phase 1 (Prérequis): {{ pgadmin_failure_reason }}"
        create: yes

    - name: "pgAdmin | Arrêt du déploiement - Phase 1"
      fail:
        msg: "❌ Déploiement pgAdmin interrompu en Phase 1 (Prérequis): {{ pgadmin_failure_reason }}"

  tags:
    - pgadmin
    - prerequisites
    - phase-1

# =========================================================================
# PHASE 2: PRÉPARATION DES RESSOURCES
# =========================================================================
- name: "pgAdmin | Phase 2 - Préparation des ressources"
  block:
    - name: "pgAdmin | Inclusion des tâches de préparation"
      include_tasks: prepare.yml
      vars:
        current_phase: "preparation"
        phase_description: "Création des ressources Kubernetes de base"

  rescue:
    - name: "pgAdmin | Échec Phase 2 - Préparation"
      set_fact:
        pgadmin_deployment_failed: true
        pgadmin_failure_phase: "preparation"
        pgadmin_failure_reason: "{{ ansible_failed_result.msg | default('Échec de la préparation') }}"

    - name: "pgAdmin | Log d'erreur Phase 2"
      lineinfile:
        path: "{{ pgadmin_error_handling.error_log_file }}"
        line: "[{{ ansible_date_time.iso8601 }}] ERREUR Phase 2 (Préparation): {{ pgadmin_failure_reason }}"
        create: yes

    - name: "pgAdmin | Nettoyage partiel après échec Phase 2"
      include_tasks: cleanup.yml
      vars:
        cleanup_scope: "preparation"
      when: pgadmin_error_handling.rollback_on_failure | bool

    - name: "pgAdmin | Arrêt du déploiement - Phase 2"
      fail:
        msg: "❌ Déploiement pgAdmin interrompu en Phase 2 (Préparation): {{ pgadmin_failure_reason }}"

  when: pgadmin_deployment_failed is not defined
  tags:
    - pgadmin
    - preparation
    - phase-2

# =========================================================================
# PHASE 3: DÉPLOIEMENT PRINCIPAL
# =========================================================================
- name: "pgAdmin | Phase 3 - Déploiement principal"
  block:
    - name: "pgAdmin | Inclusion des tâches de déploiement"
      include_tasks: deploy.yml
      vars:
        current_phase: "deployment"
        phase_description: "Déploiement des composants pgAdmin"

  rescue:
    - name: "pgAdmin | Échec Phase 3 - Déploiement"
      set_fact:
        pgadmin_deployment_failed: true
        pgadmin_failure_phase: "deployment"
        pgadmin_failure_reason: "{{ ansible_failed_result.msg | default('Échec du déploiement') }}"

    - name: "pgAdmin | Log d'erreur Phase 3"
      lineinfile:
        path: "{{ pgadmin_error_handling.error_log_file }}"
        line: "[{{ ansible_date_time.iso8601 }}] ERREUR Phase 3 (Déploiement): {{ pgadmin_failure_reason }}"
        create: yes

    - name: "pgAdmin | Rollback complet après échec Phase 3"
      include_tasks: rollback.yml
      vars:
        rollback_reason: "Échec du déploiement principal"
      when: pgadmin_error_handling.rollback_on_failure | bool

    - name: "pgAdmin | Arrêt du déploiement - Phase 3"
      fail:
        msg: "❌ Déploiement pgAdmin interrompu en Phase 3 (Déploiement): {{ pgadmin_failure_reason }}"

  when: pgadmin_deployment_failed is not defined
  tags:
    - pgadmin
    - deployment
    - phase-3

# =========================================================================
# PHASE 4: CONFIGURATION DU MONITORING
# =========================================================================
- name: "pgAdmin | Phase 4 - Configuration du monitoring"
  block:
    - name: "pgAdmin | Inclusion des tâches de monitoring"
      include_tasks: monitoring.yml
      vars:
        current_phase: "monitoring"
        phase_description: "Configuration des métriques et alertes pgAdmin"

  rescue:
    - name: "pgAdmin | Avertissement Phase 4 - Monitoring"
      debug:
        msg:
          - "⚠️  Échec de la configuration du monitoring pgAdmin"
          - "ℹ️  Le déploiement principal a réussi, mais les métriques peuvent être indisponibles"
          - "🔍 Erreur: {{ ansible_failed_result.msg | default('Erreur de monitoring inconnue') }}"

    - name: "pgAdmin | Log d'avertissement Phase 4"
      lineinfile:
        path: "{{ pgadmin_error_handling.error_log_file }}"
        line: "[{{ ansible_date_time.iso8601 }}] AVERTISSEMENT Phase 4 (Monitoring): {{ ansible_failed_result.msg | default('Erreur de monitoring') }}"
        create: yes

    - name: "pgAdmin | Marquage du monitoring comme défaillant"
      set_fact:
        pgadmin_monitoring_failed: true

  when:
    - pgadmin_deployment_failed is not defined
    - lions_monitoring_enabled | default(true) | bool
  tags:
    - pgadmin
    - monitoring
    - phase-4

# =========================================================================
# PHASE 5: VALIDATION POST-DÉPLOIEMENT
# =========================================================================
- name: "pgAdmin | Phase 5 - Validation post-déploiement"
  block:
    - name: "pgAdmin | Inclusion des tâches de validation"
      include_tasks: validate.yml
      vars:
        current_phase: "validation"
        phase_description: "Validation de l'état et des fonctionnalités pgAdmin"

  rescue:
    - name: "pgAdmin | Échec Phase 5 - Validation"
      set_fact:
        pgadmin_deployment_failed: true
        pgadmin_failure_phase: "validation"
        pgadmin_failure_reason: "{{ ansible_failed_result.msg | default('Échec de la validation') }}"

    - name: "pgAdmin | Log d'erreur Phase 5"
      lineinfile:
        path: "{{ pgadmin_error_handling.error_log_file }}"
        line: "[{{ ansible_date_time.iso8601 }}] ERREUR Phase 5 (Validation): {{ pgadmin_failure_reason }}"
        create: yes

    - name: "pgAdmin | Décision sur le rollback après validation"
      debug:
        msg: "⚠️  Validation échouée mais pgAdmin peut être partiellement fonctionnel"

    - name: "pgAdmin | Arrêt avec avertissement - Phase 5"
      fail:
        msg: "⚠️  Déploiement pgAdmin terminé avec des erreurs de validation: {{ pgadmin_failure_reason }}"

  when:
    - pgadmin_deployment_failed is not defined
    - not pgadmin_deployment_config.skip_validation | bool
  tags:
    - pgadmin
    - validation
    - phase-5

# =========================================================================
# PHASE 6: CONFIGURATION DE LA SAUVEGARDE
# =========================================================================
- name: "pgAdmin | Phase 6 - Configuration de la sauvegarde"
  block:
    - name: "pgAdmin | Inclusion des tâches de sauvegarde"
      include_tasks: backup.yml
      vars:
        current_phase: "backup"
        phase_description: "Configuration des stratégies de sauvegarde pgAdmin"

  rescue:
    - name: "pgAdmin | Avertissement Phase 6 - Sauvegarde"
      debug:
        msg:
          - "⚠️  Échec de la configuration de sauvegarde pgAdmin"
          - "ℹ️  pgAdmin fonctionne mais les sauvegardes automatiques sont désactivées"
          - "🔍 Erreur: {{ ansible_failed_result.msg | default('Erreur de sauvegarde inconnue') }}"

    - name: "pgAdmin | Log d'avertissement Phase 6"
      lineinfile:
        path: "{{ pgadmin_error_handling.error_log_file }}"
        line: "[{{ ansible_date_time.iso8601 }}] AVERTISSEMENT Phase 6 (Sauvegarde): {{ ansible_failed_result.msg | default('Erreur de sauvegarde') }}"
        create: yes

    - name: "pgAdmin | Marquage de la sauvegarde comme défaillante"
      set_fact:
        pgadmin_backup_failed: true

  when:
    - pgadmin_deployment_failed is not defined
    - lions_backup_enabled | default(true) | bool
    - lions_pgadmin_backup_enabled | default(true) | bool
  tags:
    - pgadmin
    - backup
    - phase-6

# =========================================================================
# FINALISATION ET RAPPORT DE DÉPLOIEMENT
# =========================================================================
- name: "pgAdmin | Génération du rapport de déploiement"
  set_fact:
    pgadmin_deployment_report:
      status: "{{ 'FAILED' if pgadmin_deployment_failed | default(false) else 'SUCCESS' }}"
      environment: "{{ pgadmin_deployment_metadata.environment }}"
      namespace: "{{ pgadmin_deployment_metadata.namespace }}"
      deployment_id: "{{ pgadmin_deployment_metadata.deployment_id }}"
      started_at: "{{ pgadmin_deployment_metadata.started_at }}"
      completed_at: "{{ ansible_date_time.iso8601 }}"
      duration: "{{ (ansible_date_time.epoch | int) - (pgadmin_deployment_metadata.deployment_id | int) }}"
      failed_phase: "{{ pgadmin_failure_phase | default('N/A') }}"
      failure_reason: "{{ pgadmin_failure_reason | default('N/A') }}"
      monitoring_status: "{{ 'FAILED' if pgadmin_monitoring_failed | default(false) else 'OK' }}"
      backup_status: "{{ 'FAILED' if pgadmin_backup_failed | default(false) else 'OK' }}"
      pgadmin_version: "{{ lions_pgadmin_version }}"
      pgadmin_service_name: "{{ lions_pgadmin_service_name | default('pgadmin') }}"
      pgadmin_endpoint: "{{ lions_pgadmin_service_name | default('pgadmin') }}.{{ pgadmin_deployment_metadata.namespace }}.svc.cluster.local:{{ lions_pgadmin_port | default(80) }}"
  tags:
    - pgadmin
    - report
    - always

- name: "pgAdmin | Affichage du rapport de déploiement"
  debug:
    msg:
      - "=============================================="
      - "📊 RAPPORT DE DÉPLOIEMENT PGADMIN"
      - "=============================================="
      - "📈 Statut: {{ pgadmin_deployment_report.status }}"
      - "🌍 Environnement: {{ pgadmin_deployment_report.environment }}"
      - "🏷️  Namespace: {{ pgadmin_deployment_report.namespace }}"
      - "🆔 ID de déploiement: {{ pgadmin_deployment_report.deployment_id }}"
      - "⏰ Durée: {{ pgadmin_deployment_report.duration }}s"
      - "🐘 Version pgAdmin: {{ pgadmin_deployment_report.pgadmin_version }}"
      - "🔗 Point de connexion: {{ pgadmin_deployment_report.pgadmin_endpoint }}"
      - "📊 Monitoring: {{ pgadmin_deployment_report.monitoring_status }}"
      - "💾 Sauvegarde: {{ pgadmin_deployment_report.backup_status }}"
      - "{{ '❌ Phase d\'échec: ' + pgadmin_deployment_report.failed_phase if pgadmin_deployment_report.status == 'FAILED' else '✅ Déploiement réussi' }}"
      - "{{ '🔍 Raison: ' + pgadmin_deployment_report.failure_reason if pgadmin_deployment_report.status == 'FAILED' else '' }}"
      - "=============================================="
  tags:
    - pgadmin
    - report
    - always

- name: "pgAdmin | Sauvegarde du rapport de déploiement"
  copy:
    content: "{{ pgadmin_deployment_report | to_nice_json }}"
    dest: "/tmp/pgadmin-deployment-report-{{ pgadmin_deployment_metadata.deployment_id }}.json"
  delegate_to: localhost
  tags:
    - pgadmin
    - report

# =========================================================================
# NETTOYAGE ET FINALISATION
# =========================================================================
- name: "pgAdmin | Nettoyage des fichiers temporaires"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ pgadmin_error_handling.error_log_file }}"
  when:
    - pgadmin_deployment_report.status == "SUCCESS"
    - not pgadmin_deployment_config.debug_mode | bool
  ignore_errors: yes
  tags:
    - pgadmin
    - cleanup

- name: "pgAdmin | Message de finalisation"
  debug:
    msg: |
      {% if pgadmin_deployment_report.status == 'SUCCESS' %}
      🎉 Déploiement pgAdmin terminé avec succès !

      📋 Informations de connexion:
      - Hôte: {{ pgadmin_deployment_report.pgadmin_endpoint }}
      - Port: {{ lions_pgadmin_port | default(80) }}

      📚 Documentation disponible à: https://docs.lions.dev/infrastructure/services/pgadmin
      {% else %}
      💥 Déploiement pgAdmin échoué en phase {{ pgadmin_deployment_report.failed_phase }}

      🔍 Consultez les logs d'erreur pour plus de détails:
      - Fichier d'erreur: {{ pgadmin_error_handling.error_log_file }}
      - Rapport JSON: /tmp/pgadmin-deployment-report-{{ pgadmin_deployment_metadata.deployment_id }}.json

      🛠️  Guide de dépannage: https://docs.lions.dev/infrastructure/troubleshooting/pgadmin
      {% endif %}
  tags:
    - pgadmin
    - always
