---
# Titre: Configuration du monitoring pour pgAdmin
# Description: Configure le monitoring pour pgAdmin
# Auteur: Équipe LIONS Infrastructure
# Date: 2025-05-10
# Version: 1.0.0

- name: Vérification de l'existence de Prometheus
  k8s_info:
    api_version: v1
    kind: Service
    namespace: monitoring
    name: prometheus-kube-prometheus-prometheus
  register: prometheus_info
  failed_when: false

- name: Avertissement si Prometheus n'est pas trouvé
  debug:
    msg: "AVERTISSEMENT: Le service Prometheus n'a pas été trouvé. Le monitoring de pgAdmin ne sera pas configuré."
  when: prometheus_info.resources | length == 0

- name: Création du ServiceMonitor pour pgAdmin
  k8s:
    state: present
    src: "{{ temp_dir.path }}/servicemonitor.yml"
  register: servicemonitor_result
  when:
    - prometheus_info.resources | length > 0
    - pgadmin_prometheus_scrape | default(true) | bool

- name: Configuration des règles d'alerte pour pgAdmin
  k8s:
    state: present
    definition:
      apiVersion: monitoring.coreos.com/v1
      kind: PrometheusRule
      metadata:
        name: "{{ app_name }}-alerts"
        namespace: monitoring
        labels:
          app: "{{ app_name }}"
          technology: "pgadmin"
          prometheus: kube-prometheus
      spec:
        groups:
          - name: pgadmin.rules
            rules:
              - alert: PgAdminInstanceDown
                expr: absent(up{job="{{ app_name }}"})
                for: 5m
                labels:
                  severity: critical
                annotations:
                  summary: "Instance pgAdmin {{ app_name }} down"
                  description: "L'instance pgAdmin {{ app_name }} est indisponible depuis 5 minutes."
                  runbook_url: "https://docs.lions.dev/runbooks/pgadmin-down"
  register: prometheusrule_result
  when:
    - prometheus_info.resources | length > 0
    - pgadmin_prometheus_scrape | default(true) | bool

- name: Affichage des informations sur le monitoring
  debug:
    msg: "Le monitoring a été configuré pour pgAdmin. ServiceMonitor: {{ servicemonitor_result.changed | default(false) }}, PrometheusRule: {{ prometheusrule_result.changed | default(false) }}"
  when:
    - prometheus_info.resources | length > 0
    - pgadmin_prometheus_scrape | default(true) | bool