apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
data:
  APP_NAME: {{ .Values.name }}
  APP_ENV: {{ .Values.environment }}