---
# Titre: Vérification des prérequis pour la registry de conteneurs
# Description: Vérifie que tous les prérequis sont satisfaits pour déployer la registry
# Auteur: Équipe LIONS Infrastructure
# Date: 2025-05-10
# Version: 1.0.0

- name: Vérification de l'existence du namespace
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Namespace
    name: "{{ app_namespace | default('registry') }}"
  register: namespace_info
  failed_when: false

- name: Création du namespace si nécessaire
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ app_namespace | default('registry') }}"
        labels:
          name: "{{ app_namespace | default('registry') }}"
          app: "{{ app_name | default('registry') }}"
          environment: "{{ app_environment | default('production') }}"
  when: namespace_info.resources | length == 0

- name: Vérification des droits d'accès
  kubernetes.core.k8s_info:
    api_version: rbac.authorization.k8s.io/v1
    kind: Role
    name: "{{ app_name }}-role"
    namespace: "{{ app_namespace | default('registry') }}"
  register: role_info
  failed_when: false

- name: Avertissement si les droits d'accès ne sont pas configurés
  debug:
    msg: "AVERTISSEMENT: Les droits d'accès pour la registry ne sont pas configurés. Certaines fonctionnalités pourraient ne pas fonctionner correctement."
  when: role_info.resources | length == 0

- name: Vérification de l'existence du contrôleur d'ingress (Traefik)
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: kube-system
    label_selectors:
      - app=traefik
  register: ingress_info
  failed_when: false

- name: Avertissement si le contrôleur d'ingress n'est pas trouvé
  debug:
    msg: "AVERTISSEMENT: Le contrôleur d'ingress Traefik n'a pas été trouvé. La registry ne sera pas accessible depuis l'extérieur."
  when: ingress_info.resources | length == 0

- name: Vérification de la classe de stockage
  kubernetes.core.k8s_info:
    api_version: storage.k8s.io/v1
    kind: StorageClass
    name: "{{ registry_storage_class | default('standard') }}"
  register: storage_class_info
  failed_when: false

- name: Avertissement si la classe de stockage n'est pas trouvée
  debug:
    msg: "AVERTISSEMENT: La classe de stockage {{ registry_storage_class | default('standard') }} n'a pas été trouvée. La registry nécessite un stockage persistant pour fonctionner correctement."
  when: storage_class_info.resources | length == 0

- name: Vérification des ressources disponibles sur les nœuds
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Node
  register: nodes_info

- name: Avertissement sur les ressources
  debug:
    msg: "AVERTISSEMENT: Vérifiez que les nœuds disposent de suffisamment de ressources pour la registry. Ressources recommandées: 1 CPU, 2Gi mémoire, 10Gi stockage."
  when: nodes_info.resources | length > 0
