---
# Titre: Déploiement de Keycloak
# Description: Déploie Keycloak sur Kubernetes
# Auteur: Équipe LIONS Infrastructure
# Date: 2025-05-07
# Version: 1.0.0

- name: Déploiement de Keycloak
  k8s:
    state: present
    src: "{{ temp_dir.path }}/deployment.yml"
  register: deployment_result

- name: Création du service pour Keycloak
  k8s:
    state: present
    src: "{{ temp_dir.path }}/service.yml"
  register: service_result

- name: Création de l'ingress pour Keycloak
  k8s:
    state: present
    src: "{{ temp_dir.path }}/ingress.yml"
  register: ingress_result
  when: app_environment != 'development' or (extra_params.create_ingress | default(true) | bool)

- name: Attente du déploiement
  k8s_info:
    api_version: apps/v1
    kind: Deployment
    namespace: "{{ app_namespace }}"
    name: "{{ app_name }}"
  register: deployment_status
  until: deployment_status.resources[0].status.availableReplicas is defined and deployment_status.resources[0].status.availableReplicas == deployment_status.resources[0].spec.replicas
  retries: 30
  delay: 10
  ignore_errors: yes

- name: Vérification du statut du déploiement
  fail:
    msg: "Le déploiement de Keycloak a échoué. Veuillez vérifier les logs pour plus d'informations."
  when: deployment_status is failed or deployment_status.resources | length == 0

- name: Récupération des informations sur les pods
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ app_namespace }}"
    label_selectors:
      - "app={{ app_name }}"
  register: pods_info

- name: Affichage des informations sur les pods
  debug:
    msg: "Pod {{ item.metadata.name }} est dans l'état {{ item.status.phase }}"
  loop: "{{ pods_info.resources }}"
  loop_control:
    label: "{{ item.metadata.name }}"

- name: Attente de l'initialisation de Keycloak
  pause:
    seconds: "{{ keycloak_init_delay | default(60) }}"
  when: deployment_status is succeeded

- name: Vérification de l'état des pods après initialisation
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ app_namespace }}"
    label_selectors:
      - "app={{ app_name }}"
  register: pods_info_after_init

- name: Affichage des informations sur les pods après initialisation
  debug:
    msg: "Pod {{ item.metadata.name }} est dans l'état {{ item.status.phase }} après initialisation"
  loop: "{{ pods_info_after_init.resources }}"
  loop_control:
    label: "{{ item.metadata.name }}"

- name: Vérification des logs des pods pour détecter des erreurs
  shell: "kubectl logs -n {{ app_namespace }} {{ item.metadata.name }} | grep -i error | tail -10"
  loop: "{{ pods_info_after_init.resources }}"
  register: pod_logs
  ignore_errors: yes
  changed_when: false
  loop_control:
    label: "{{ item.metadata.name }}"

- name: Affichage des erreurs dans les logs (si présentes)
  debug:
    msg: "Erreurs détectées dans les logs de {{ item.item.metadata.name }}: {{ item.stdout }}"
  loop: "{{ pod_logs.results }}"
  when: item.stdout != ""
  loop_control:
    label: "{{ item.item.metadata.name }}"

- name: Vérification de la disponibilité de l'API Keycloak
  uri:
    url: "http://{{ app_name }}.{{ app_namespace }}.svc.cluster.local:{{ keycloak_default_port }}{{ keycloak_health_path }}/ready"
    method: GET
    status_code: 200
  register: api_check
  ignore_errors: yes
  retries: 5
  delay: 10
  until: api_check is succeeded

- name: Avertissement si l'API Keycloak n'est pas disponible
  debug:
    msg: "AVERTISSEMENT: L'API de Keycloak n'est pas disponible. Vérifiez les logs pour plus d'informations."
  when: api_check is failed

- name: Vérification de la connexion à la base de données
  uri:
    url: "http://{{ app_name }}.{{ app_namespace }}.svc.cluster.local:{{ keycloak_default_port }}/health/ready"
    method: GET
    status_code: 200
  register: db_check
  ignore_errors: yes
  retries: 3
  delay: 5
  until: db_check is succeeded

- name: Avertissement si la connexion à la base de données n'est pas fonctionnelle
  debug:
    msg: "AVERTISSEMENT: La connexion à la base de données n'est pas fonctionnelle. Vérifiez les logs et la configuration de la base de données."
  when: db_check is failed