---
# Titre: Variables pour le déploiement d'applications PrimeReact
# Description: Variables spécifiques aux applications PrimeReact
# Auteur: Équipe LIONS Infrastructure
# Date: 2025-05-07
# Version: 1.0.0

# Configuration par défaut pour PrimeReact
primereact_default_port: 3000
primereact_health_path: "/api/health"
primereact_profile: "{{ app_environment }}"
primereact_use_redis: false
primereact_create_networkpolicy: true

# Configuration des sondes de santé
primereact_readiness_probe:
  httpGet:
    path: "{{ primereact_health_path }}"
    port: http
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

primereact_liveness_probe:
  httpGet:
    path: "{{ primereact_health_path }}"
    port: http
  initialDelaySeconds: 40
  periodSeconds: 20
  timeoutSeconds: 3
  failureThreshold: 3

# Configuration du monitoring
primereact_prometheus_port: 3000
primereact_prometheus_path: "/metrics"
primereact_prometheus_scrape: true
primereact_init_delay: 20

# Configuration des ressources par environnement
primereact_resources:
  development:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  staging:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
  production:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2000m"
      memory: "2Gi"

# Configuration des réplicas par environnement
primereact_replicas:
  development: 1
  staging: 2
  production: 3

# Configuration de l'ingress
primereact_ingress_annotations:
  kubernetes.io/ingress.class: "nginx"
  cert-manager.io/cluster-issuer: "letsencrypt-prod"
  nginx.ingress.kubernetes.io/ssl-redirect: "true"
  nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  nginx.ingress.kubernetes.io/configuration-snippet: |
    more_set_headers "X-Frame-Options: SAMEORIGIN";
    more_set_headers "X-XSS-Protection: 1; mode=block";
    more_set_headers "X-Content-Type-Options: nosniff";

# Configuration Redis (optionnel)
primereact_redis_service: "{{ app_name }}-redis"
primereact_redis_port: 6379

# Configuration Node.js
primereact_node_env: "{{ app_environment }}"
primereact_node_options: "--max-old-space-size=512"

# Configuration spécifique à PrimeReact
primereact_theme: "saga"
primereact_ripple: true
primereact_responsive: true