---
# Titre: Limites de ressources par défaut
# Description: Définit les limites de ressources par défaut pour les conteneurs
# Auteur: Équipe LIONS Infrastructure
# Date: 2025-05-16
# Version: 1.0.0

# Limites de ressources pour le namespace default
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: default
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
---
# Limites de ressources pour le namespace development
apiVersion: v1
kind: LimitRange
metadata:
  name: development-limits
  namespace: development
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: "2"
      memory: "2Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
    type: Container
---
# Limites de ressources pour le namespace monitoring
apiVersion: v1
kind: LimitRange
metadata:
  name: monitoring-limits
  namespace: monitoring
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: "4"
      memory: "4Gi"
    type: Container
---
# Limites de ressources pour le namespace cert-manager
apiVersion: v1
kind: LimitRange
metadata:
  name: cert-manager-limits
  namespace: cert-manager
spec:
  limits:
  - default:
      cpu: "200m"
      memory: "256Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: "1"
      memory: "1Gi"
    type: Container
---
# Limites de ressources pour le namespace kubernetes-dashboard
apiVersion: v1
kind: LimitRange
metadata:
  name: kubernetes-dashboard-limits
  namespace: kubernetes-dashboard
spec:
  limits:
  - default:
      cpu: "200m"
      memory: "256Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: "1"
      memory: "1Gi"
    type: Container
---
# Limites de ressources pour le namespace lions-infrastructure
apiVersion: v1
kind: LimitRange
metadata:
  name: lions-infrastructure-limits
  namespace: lions-infrastructure
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: "2"
      memory: "2Gi"
    type: Container
---
# Limites de ressources pour les namespaces spécifiques aux applications
apiVersion: v1
kind: LimitRange
metadata:
  name: postgres-development-limits
  namespace: postgres-development
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "500m"
      memory: "512Mi"
    max:
      cpu: "2"
      memory: "4Gi"
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: pgadmin-development-limits
  namespace: pgadmin-development
spec:
  limits:
  - default:
      cpu: "200m"
      memory: "256Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: "500m"
      memory: "512Mi"
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: gitea-development-limits
  namespace: gitea-development
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "200m"
      memory: "256Mi"
    max:
      cpu: "1"
      memory: "1Gi"
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: keycloak-development-limits
  namespace: keycloak-development
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "500m"
      memory: "512Mi"
    max:
      cpu: "2"
      memory: "2Gi"
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: ollama-development-limits
  namespace: ollama-development
spec:
  limits:
  - default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "1"
      memory: "2Gi"
    max:
      cpu: "4"
      memory: "8Gi"
    type: Container