# Titre: Quotas de ressources par défaut
# Description: Définit les quotas de ressources par défaut pour l'infrastructure LIONS
# Auteur: Équipe LIONS Infrastructure
# Date: 2025-05-08
# Version: 1.0.0

apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  labels:
    app.kubernetes.io/part-of: lions-infrastructure
spec:
  hard:
    requests.cpu: '8'
    requests.memory: 16Gi
    limits.cpu: '16'
    limits.memory: 32Gi
    pods: '50'
    services: '30'
    persistentvolumeclaims: '20'
    secrets: '30'
    configmaps: '30'