---
# Titre: Playbook d'installation de K3s
# Description: Installe et configure K3s sur le VPS
# Auteur: Équipe LIONS Infrastructure
# Date: 2023-05-15
# Version: 1.0.0

- name: Installation de K3s sur le VPS
  hosts: vps
  become: yes

  vars:
    k3s_version: "v1.25.6+k3s1"  # Version stable de K3s
    k3s_server_args: "--disable servicelb --disable-cloud-controller --kube-controller-manager-arg bind-address=0.0.0.0 --kube-scheduler-arg bind-address=0.0.0.0"
    kubeconfig_local_path: "~/.kube/config"

  tasks:
    - name: Vérification de l'installation existante de K3s
      stat:
        path: /usr/local/bin/k3s
      register: k3s_binary

    - name: Téléchargement du script d'installation K3s
      get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s-install.sh
        mode: '0755'
      when: not k3s_binary.stat.exists

    - name: Installation de K3s
      environment:
        INSTALL_K3S_VERSION: "{{ k3s_version }}"
        INSTALL_K3S_EXEC: "{{ k3s_server_args }}"
      command: /tmp/k3s-install.sh
      args:
        creates: /usr/local/bin/k3s
      register: k3s_installed
      when: not k3s_binary.stat.exists

    - name: Attente que K3s soit prêt
      wait_for:
        path: /var/lib/rancher/k3s/server/node-token
        state: present
        delay: 10
        timeout: 300
      when: k3s_installed.changed

    - name: Attente que le serveur API K3s soit prêt
      wait_for:
        port: 6443
        delay: 10
        timeout: 300
      when: k3s_installed.changed

    - name: Création du répertoire .kube pour l'utilisateur
      file:
        path: /home/{{ ansible_user }}/.kube
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Copie du fichier kubeconfig pour l'utilisateur
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/{{ ansible_user }}/.kube/config
        remote_src: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'

    - name: Mise à jour du fichier kubeconfig avec l'adresse IP externe
      replace:
        path: /home/{{ ansible_user }}/.kube/config
        regexp: 'https://127.0.0.1:6443'
        replace: 'https://{{ ansible_host }}:6443'

    - name: Configuration de l'accès à kubectl
      lineinfile:
        path: /home/{{ ansible_user }}/.bashrc
        line: 'export KUBECONFIG=/home/{{ ansible_user }}/.kube/config'
        state: present

    - name: Installation de kubectl
      block:
        - name: Ajout de la clé GPG de Kubernetes
          apt_key:
            url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
            state: present

        - name: Ajout du dépôt Kubernetes
          apt_repository:
            repo: deb https://apt.kubernetes.io/ kubernetes-focal main
            state: present
            filename: kubernetes

        - name: Installation de kubectl
          apt:
            name: kubectl
            state: present
            update_cache: yes
      when: not k3s_binary.stat.exists

    - name: Récupération du fichier kubeconfig pour utilisation locale
      fetch:
        src: /home/{{ ansible_user }}/.kube/config
        dest: "{{ kubeconfig_local_path }}"
        flat: yes
      when: kubeconfig_local_path is defined

    - name: Installation de Helm
      block:
        - name: Téléchargement du script d'installation de Helm
          get_url:
            url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
            dest: /tmp/get-helm-3.sh
            mode: '0755'

        - name: Exécution du script d'installation de Helm
          command: /tmp/get-helm-3.sh
          args:
            creates: /usr/local/bin/helm

        - name: Configuration de Helm pour utiliser le bon kubeconfig
          lineinfile:
            path: /home/{{ ansible_user }}/.bashrc
            line: 'export KUBECONFIG=/home/{{ ansible_user }}/.kube/config'
            state: present

        # Pas besoin de recharger l'environnement, on va utiliser le paramètre environment pour les tâches Helm

        - name: Vérification que le répertoire /root/.kube existe
          file:
            path: /root/.kube
            state: directory
            mode: '0755'
          become: yes

        - name: Création d'un lien symbolique pour le kubeconfig dans /root/.kube
          file:
            src: /home/{{ ansible_user }}/.kube/config
            dest: /root/.kube/config
            state: link
            force: yes
          become: yes

    - name: Vérification de l'installation de K3s
      command: k3s kubectl get nodes
      register: k3s_nodes
      changed_when: false
      environment:
        KUBECONFIG: /home/{{ ansible_user }}/.kube/config

    - name: Affichage des nœuds K3s
      debug:
        var: k3s_nodes.stdout_lines

    - name: Vérification des pods système
      command: k3s kubectl get pods -n kube-system
      register: k3s_system_pods
      changed_when: false
      environment:
        KUBECONFIG: /home/{{ ansible_user }}/.kube/config

    - name: Affichage des pods système
      debug:
        var: k3s_system_pods.stdout_lines

    - name: Installation de MetalLB pour le LoadBalancer
      block:
        - name: Création du namespace metallb-system
          k8s:
            name: metallb-system
            api_version: v1
            kind: Namespace
            state: present
          environment:
            KUBECONFIG: /home/{{ ansible_user }}/.kube/config

        - name: Déploiement de MetalLB via Helm
          kubernetes.core.helm:
            name: metallb
            chart_ref: metallb/metallb
            release_namespace: metallb-system
            create_namespace: true
            wait: true
          environment:
            KUBECONFIG: /home/{{ ansible_user }}/.kube/config

        - name: Configuration de l'IPAddressPool pour MetalLB
          k8s:
            state: present
            definition:
              apiVersion: metallb.io/v1beta1
              kind: IPAddressPool
              metadata:
                name: first-pool
                namespace: metallb-system
              spec:
                addresses:
                  - "{{ ansible_host }}/32"  # Utilise l'adresse IP du VPS
          environment:
            KUBECONFIG: /home/{{ ansible_user }}/.kube/config

        - name: Configuration de L2Advertisement pour MetalLB
          k8s:
            state: present
            definition:
              apiVersion: metallb.io/v1beta1
              kind: L2Advertisement
              metadata:
                name: l2-advert
                namespace: metallb-system
              spec:
                ipAddressPools:
                  - first-pool
          environment:
            KUBECONFIG: /home/{{ ansible_user }}/.kube/config
      when: k3s_installed.changed

    - name: Installation de cert-manager pour les certificats TLS
      block:
        - name: Ajout du dépôt Helm de cert-manager
          kubernetes.core.helm_repository:
            name: jetstack
            repo_url: https://charts.jetstack.io
          environment:
            KUBECONFIG: /home/{{ ansible_user }}/.kube/config

        - name: Déploiement de cert-manager via Helm
          kubernetes.core.helm:
            name: cert-manager
            chart_ref: jetstack/cert-manager
            release_namespace: cert-manager
            create_namespace: true
            wait: true
            set_values:
              - value: installCRDs=true
          environment:
            KUBECONFIG: /home/{{ ansible_user }}/.kube/config

    # Traefik est maintenant utilisé comme contrôleur d'ingress par défaut
    # Le bloc d'installation de Nginx Ingress Controller a été supprimé
    # Traefik est installé automatiquement avec K3s

    - name: Installation du Kubernetes Dashboard
      block:
        - name: Création du namespace kubernetes-dashboard
          k8s:
            name: kubernetes-dashboard
            api_version: v1
            kind: Namespace
            state: present
          environment:
            KUBECONFIG: /home/{{ ansible_user }}/.kube/config

        - name: Déploiement du Kubernetes Dashboard
          k8s:
            state: present
            src: https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml
          environment:
            KUBECONFIG: /home/{{ ansible_user }}/.kube/config

        - name: Création du Service NodePort pour exposer le Dashboard
          k8s:
            state: present
            definition:
              apiVersion: v1
              kind: Service
              metadata:
                name: kubernetes-dashboard-nodeport
                namespace: kubernetes-dashboard
              spec:
                ports:
                - port: 443
                  targetPort: 8443
                  nodePort: 30001
                selector:
                  k8s-app: kubernetes-dashboard
                type: NodePort
          environment:
            KUBECONFIG: /home/{{ ansible_user }}/.kube/config

        - name: Création d'un compte de service avec droits d'administration
          k8s:
            state: present
            definition:
              apiVersion: v1
              kind: ServiceAccount
              metadata:
                name: dashboard-admin
                namespace: kubernetes-dashboard
          environment:
            KUBECONFIG: /home/{{ ansible_user }}/.kube/config

        - name: Création d'un ClusterRoleBinding pour le compte admin
          k8s:
            state: present
            definition:
              apiVersion: rbac.authorization.k8s.io/v1
              kind: ClusterRoleBinding
              metadata:
                name: dashboard-admin
              roleRef:
                apiGroup: rbac.authorization.k8s.io
                kind: ClusterRole
                name: cluster-admin
              subjects:
              - kind: ServiceAccount
                name: dashboard-admin
                namespace: kubernetes-dashboard
          environment:
            KUBECONFIG: /home/{{ ansible_user }}/.kube/config

        - name: Création de l'Ingress pour le Kubernetes Dashboard (Production)
          k8s:
            state: present
            definition:
              apiVersion: networking.k8s.io/v1
              kind: Ingress
              metadata:
                name: kubernetes-dashboard-prod
                namespace: kubernetes-dashboard
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt-prod
                  traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
                  traefik.ingress.kubernetes.io/router.tls: "true"
                  traefik.ingress.kubernetes.io/router.middlewares: "kubernetes-dashboard-strip-prefix@kubernetescrd"
              spec:
                ingressClassName: traefik
                tls:
                  - hosts:
                      - "k3s.lions.dev"
                    secretName: kubernetes-dashboard-tls-prod
                rules:
                  - host: "k3s.lions.dev"
                    http:
                      paths:
                        - path: /
                          pathType: Prefix
                          backend:
                            service:
                              name: kubernetes-dashboard
                              port:
                                number: 443
          environment:
            KUBECONFIG: /home/{{ ansible_user }}/.kube/config

        - name: Création de l'Ingress pour le Kubernetes Dashboard (Développement)
          k8s:
            state: present
            definition:
              apiVersion: networking.k8s.io/v1
              kind: Ingress
              metadata:
                name: kubernetes-dashboard-dev
                namespace: kubernetes-dashboard
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt-staging
                  traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
                  traefik.ingress.kubernetes.io/router.tls: "true"
                  traefik.ingress.kubernetes.io/router.middlewares: "kubernetes-dashboard-strip-prefix@kubernetescrd"
              spec:
                ingressClassName: traefik
                tls:
                  - hosts:
                      - "k3s.dev.lions.dev"
                    secretName: kubernetes-dashboard-tls-dev
                rules:
                  - host: "k3s.dev.lions.dev"
                    http:
                      paths:
                        - path: /
                          pathType: Prefix
                          backend:
                            service:
                              name: kubernetes-dashboard
                              port:
                                number: 443
          environment:
            KUBECONFIG: /home/{{ ansible_user }}/.kube/config

        - name: Création du middleware pour le Dashboard
          k8s:
            state: present
            definition:
              apiVersion: traefik.containo.us/v1alpha1
              kind: Middleware
              metadata:
                name: kubernetes-dashboard-strip-prefix
                namespace: kubernetes-dashboard
              spec:
                stripPrefix:
                  prefixes:
                    - "/dashboard"
          environment:
            KUBECONFIG: /home/{{ ansible_user }}/.kube/config

        - name: Génération d'un token pour l'accès au Dashboard
          command: k3s kubectl create token dashboard-admin -n kubernetes-dashboard
          register: dashboard_token
          changed_when: false
          environment:
            KUBECONFIG: /home/{{ ansible_user }}/.kube/config

        - name: Affichage du token pour l'accès au Dashboard
          debug:
            msg: "Token pour l'accès au Kubernetes Dashboard: {{ dashboard_token.stdout }}"

    - name: Vérification finale de l'installation
      debug:
        msg: "K3s a été installé avec succès sur le VPS et est prêt à recevoir les applications."
