---
# =============================================================================
# LIONS INFRASTRUCTURE 5.0 - INVENTAIRE DÉVELOPPEMENT
# =============================================================================
# Description: Configuration des hôtes pour l'environnement de développement
# Version: 5.0.0
# Date: 2025-05-26
# Maintainer: DevOps Team LIONS
# Documentation: https://docs.lions.dev/infrastructure/inventory
# =============================================================================

# =============================================================================
# DÉFINITION DES GROUPES D'HÔTES
# =============================================================================
all:
  children:
    # -----------------------------------------------------------------------------
    # INFRASTRUCTURE PRINCIPALE
    # -----------------------------------------------------------------------------
    lions_infrastructure:
      children:
        # Serveurs VPS/Bare Metal
        vps_servers:
          hosts:
            lions-dev-primary:
              # Configuration de connexion
              ansible_host: "{{ lions_infra_target_host | default('127.0.0.1') }}"
              ansible_port: "{{ lions_infra_target_port | default(225) }}"
              ansible_user: "{{ lions_infra_target_user | default('lions-admin') }}"
              ansible_python_interpreter: /usr/bin/python3
              ansible_ssh_private_key_file: "{{ lions_infra_ssh_key_path | default('~/.ssh/lions_infrastructure_rsa') }}"

              # Métadonnées de l'hôte
              host_role: primary
              host_environment: development
              host_datacenter: contabo-eu
              host_provider: contabo

              # Configuration réseau
              internal_ip: "{{ ansible_host }}"
              external_ip: "{{ ansible_host }}"
              network_interface: eth0

              # Spécifications matérielles
              cpu_cores: 4
              memory_gb: 8
              storage_gb: 200
              storage_type: ssd

              # Configuration de sécurité
              ssh_hardening_enabled: true
              fail2ban_enabled: true
              ufw_firewall_enabled: true
              automatic_updates_enabled: true

        # -----------------------------------------------------------------------------
        # CLUSTER KUBERNETES
        # -----------------------------------------------------------------------------
        kubernetes_cluster:
          children:
            # Nœuds de contrôle K3s
            k3s_control_plane:
              hosts:
                lions-dev-primary:
                  # Configuration K3s
                  k3s_role: server
                  k3s_node_type: control-plane
                  k3s_server_init: true
                  k3s_server_taint: true

                  # Configuration haute disponibilité (désactivée en dev)
                  k3s_ha_enabled: false
                  k3s_embedded_etcd: true

                  # Configuration réseau K3s
                  k3s_cluster_cidr: "{{ lions_k8s_cluster_cidr | default('10.42.0.0/16') }}"
                  k3s_service_cidr: "{{ lions_k8s_service_cidr | default('10.43.0.0/16') }}"
                  k3s_cluster_dns: "{{ lions_k8s_dns_domain | default('cluster.local') }}"

                  # Configuration des composants
                  k3s_traefik_enabled: "{{ lions_k8s_traefik_enabled | default(true) }}"
                  k3s_metallb_enabled: "{{ lions_k8s_metallb_enabled | default(true) }}"
                  k3s_metrics_server_enabled: true

                  # Configuration du stockage
                  k3s_default_storage_class: "{{ lions_storage_class_default | default('local-path') }}"

            # Nœuds workers K3s (vide en développement single-node)
            k3s_workers:
              hosts: {}
              # Exemple pour l'ajout futur de workers:
              # lions-dev-worker-1:
              #   k3s_role: agent
              #   k3s_node_type: worker
              #   k3s_server_url: "https://{{ hostvars['lions-dev-primary']['internal_ip'] }}:6443"

        # -----------------------------------------------------------------------------
        # SERVICES D'INFRASTRUCTURE
        # -----------------------------------------------------------------------------
        infrastructure_services:
          children:
            # Serveurs de stockage de secrets
            vault_servers:
              hosts:
                lions-dev-primary:
                  vault_node_role: standalone
                  vault_datacenter: dc1
                  vault_storage_type: file
                  vault_ui_enabled: true
                  vault_api_port: "{{ lions_vault_port | default(8200) }}"
                  vault_cluster_port: 8201
                  vault_data_dir: "{{ lions_vault_data_dir | default('/opt/vault/data') }}"
                  vault_config_dir: "{{ lions_vault_config_dir | default('/etc/vault.d') }}"
                  vault_log_level: "{{ lions_log_level | default('INFO') }}"

            # Serveurs de bases de données
            database_servers:
              hosts:
                lions-dev-primary:
                  # PostgreSQL
                  postgres_enabled: "{{ lions_postgres_enabled | default(true) }}"
                  postgres_version: "{{ lions_postgres_version | default('15.4') }}"
                  postgres_port: "{{ lions_postgres_port | default(5432) }}"
                  postgres_database: "{{ lions_postgres_database | default('lions_db') }}"
                  postgres_max_connections: 100
                  postgres_shared_buffers: "256MB"

                  # Redis
                  redis_enabled: "{{ lions_redis_enabled | default(true) }}"
                  redis_version: "{{ lions_redis_version | default('7.2') }}"
                  redis_port: "{{ lions_redis_port | default(6379) }}"
                  redis_maxmemory: "512mb"
                  redis_maxmemory_policy: "allkeys-lru"

        # -----------------------------------------------------------------------------
        # SERVICES APPLICATIFS
        # -----------------------------------------------------------------------------
        application_services:
          children:
            # Services de sécurité et identité
            security_services:
              hosts:
                lions-dev-primary:
                  # Keycloak
                  keycloak_enabled: "{{ lions_keycloak_enabled | default(true) }}"
                  keycloak_version: "{{ lions_keycloak_version | default('22.0') }}"
                  keycloak_port: "{{ lions_keycloak_port | default(8080) }}"
                  keycloak_realm: "{{ lions_keycloak_realm | default('lions') }}"
                  keycloak_admin_user: "{{ lions_keycloak_admin_user | default('admin') }}"
                  keycloak_db_vendor: postgres
                  keycloak_health_enabled: true

            # Services de développement
            development_services:
              hosts:
                lions-dev-primary:
                  # Gitea
                  gitea_enabled: "{{ lions_gitea_enabled | default(true) }}"
                  gitea_version: "{{ lions_gitea_version | default('1.20.5') }}"
                  gitea_port: "{{ lions_gitea_port | default(3000) }}"
                  gitea_db_type: postgres
                  gitea_ssh_port: 2222

                  # Registry
                  registry_enabled: "{{ lions_registry_enabled | default(true) }}"
                  registry_version: "{{ lions_registry_version | default('2.8') }}"
                  registry_port: "{{ lions_registry_port | default(5000) }}"
                  registry_auth_enabled: true
                  registry_tls_enabled: "{{ lions_security_tls_enabled | default(true) }}"

            # Services d'intelligence artificielle
            ai_services:
              hosts:
                lions-dev-primary:
                  # Ollama
                  ollama_enabled: "{{ lions_ollama_enabled | default(true) }}"
                  ollama_version: "{{ lions_ollama_version | default('0.1.26') }}"
                  ollama_port: "{{ lions_ollama_port | default(11434) }}"
                  ollama_gpu_enabled: "{{ lions_ollama_gpu_enabled | default(false) }}"
                  ollama_models_dir: /opt/ollama/models
                  ollama_default_models:
                    - llama2:7b
                    - codellama:7b

        # -----------------------------------------------------------------------------
        # SERVICES DE MONITORING
        # -----------------------------------------------------------------------------
        monitoring_services:
          hosts:
            lions-dev-primary:
              # Prometheus
              prometheus_enabled: "{{ lions_prometheus_enabled | default(true) }}"
              prometheus_version: "{{ lions_prometheus_version | default('2.45.0') }}"
              prometheus_retention_time: "{{ lions_prometheus_retention | default('30d') }}"
              prometheus_storage_size: "{{ lions_prometheus_storage_size | default('50Gi') }}"
              prometheus_scrape_interval: 15s
              prometheus_evaluation_interval: 15s

              # Grafana
              grafana_enabled: "{{ lions_grafana_enabled | default(true) }}"
              grafana_version: "{{ lions_grafana_version | default('10.1.0') }}"
              grafana_admin_user: "{{ lions_grafana_admin_user | default('admin') }}"
              grafana_enable_provisioning: true
              grafana_datasources_provisioning: true

              # Alertmanager
              alertmanager_enabled: "{{ lions_alertmanager_enabled | default(true) }}"
              alertmanager_version: "{{ lions_alertmanager_version | default('0.25.0') }}"
              alertmanager_cluster_enabled: false

              # Loki (Logging)
              loki_enabled: "{{ lions_loki_enabled | default(true) }}"
              loki_version: "{{ lions_loki_version | default('2.9.0') }}"
              loki_retention_period: "{{ lions_backup_retention_days | default(30) }}d"

  # =============================================================================
  # VARIABLES GLOBALES
  # =============================================================================
  vars:
    # -----------------------------------------------------------------------------
    # CONFIGURATION D'AUTHENTIFICATION
    # -----------------------------------------------------------------------------
    # Authentification SSH
    ansible_user: "{{ lions_infra_target_user | default('lions-admin') }}"
    ansible_become: true
    ansible_become_method: sudo
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

    # Configuration des timeouts
    ansible_ssh_timeout: 30
    ansible_connect_timeout: 10
    ansible_command_timeout: "{{ lions_timeout_default | default(300) }}"

    # -----------------------------------------------------------------------------
    # VARIABLES D'ENVIRONNEMENT GLOBALES
    # -----------------------------------------------------------------------------
    # Environnement et domaine
    lions_environment: development
    lions_domain_base: "{{ lions_dns_domain_base | default('lions.local') }}"
    lions_full_domain: "dev.{{ lions_domain_base }}"

    # Configuration de sécurité
    lions_security_hardening: true
    lions_security_tls_enabled: "{{ lions_security_tls_enabled | default(true) }}"
    lions_security_tls_staging: true  # Utilise Let's Encrypt staging en dev
    lions_security_network_policies: "{{ lions_security_network_policies | default(true) }}"

    # Configuration des logs
    lions_log_level: "{{ lions_log_level | default('DEBUG') }}"
    lions_debug_mode: "{{ lions_debug_mode | default(true) }}"

    # Configuration des ressources (profil développement - ressources réduites)
    lions_resources_profile: small
    lions_cpu_request: "{{ lions_resources_small_cpu_request | default('100m') }}"
    lions_cpu_limit: "{{ lions_resources_small_cpu_limit | default('500m') }}"
    lions_memory_request: "{{ lions_resources_small_memory_request | default('128Mi') }}"
    lions_memory_limit: "{{ lions_resources_small_memory_limit | default('512Mi') }}"

    # Configuration des backups (réduite en développement)
    lions_backup_enabled: "{{ lions_backup_enabled | default(false) }}"
    lions_backup_retention_days: 7
    lions_backup_external_enabled: false

    # -----------------------------------------------------------------------------
    # CONFIGURATION SPÉCIFIQUE AU DÉVELOPPEMENT
    # -----------------------------------------------------------------------------
    # Optimisations pour le développement
    development_optimizations:
      # Réduction des ressources pour économiser les ressources système
      resource_limits_relaxed: true
      # Activation du mode debug pour tous les services
      debug_mode_global: true
      # Désactivation des fonctionnalités non critiques
      backup_disabled: true
      monitoring_light_mode: true
      # Activation de l'auto-reload pour le développement
      hot_reload_enabled: true
      # Configuration de développement pour les bases de données
      database_dev_mode: true

    # URLs de développement
    service_urls:
      vault: "https://vault.{{ lions_full_domain }}"
      grafana: "https://grafana.{{ lions_full_domain }}"
      prometheus: "https://prometheus.{{ lions_full_domain }}"
      keycloak: "https://auth.{{ lions_full_domain }}"
      gitea: "https://git.{{ lions_full_domain }}"
      registry: "https://registry.{{ lions_full_domain }}"
      ollama: "https://ai.{{ lions_full_domain }}"

    # Configuration de la persistence (développement = volatile)
    persistence_config:
      storage_class: "{{ lions_storage_class_default | default('local-path') }}"
      backup_enabled: false
      volume_reclaim_policy: Delete  # Suppression automatique en dev

    # -----------------------------------------------------------------------------
    # INTÉGRATION AVEC LES VARIABLES D'ENVIRONNEMENT
    # -----------------------------------------------------------------------------
    # Ces variables font le lien avec le fichier .env principal
    env_file_path: "{{ playbook_dir }}/../../.env"
    env_validation_required: true
    env_override_allowed: true

# =============================================================================
# GROUPES FONCTIONNELS POUR LES PLAYBOOKS
# =============================================================================
# Ces groupes simplifient l'exécution des playbooks spécifiques
ungrouped: {}

# Groupes pour l'exécution sélective
lions_core:
  children:
    vps_servers: {}
    k3s_control_plane: {}
    vault_servers: {}

lions_data:
  children:
    database_servers: {}

lions_apps:
  children:
    application_services: {}

lions_monitoring:
  children:
    monitoring_services: {}

# =============================================================================
# FIN DE L'INVENTAIRE
# =============================================================================