---
all:
  children:
    vps:
      hosts:
        contabo-vps:
          ansible_host: 176.57.150.2
          ansible_port: 22225  # Port SSH personnalisé
          ansible_user: lionsdevadmin
          ansible_python_interpreter: /usr/bin/python3
    kubernetes:
      hosts:
        contabo-vps:
          ansible_host: 176.57.150.2
          ansible_port: 22225  # Même port SSH personnalisé
    databases:
      hosts:
        contabo-vps:
          ansible_host: 176.57.150.2
          ansible_port: 22225  # Même port SSH personnalisé
    monitoring:
      hosts:
        contabo-vps:
          ansible_host: 176.57.150.2
          ansible_port: 22225  # Même port SSH personnalisé
  vars:
    ansible_user: lionsdevadmin
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_become: yes
    environment: development
    domain_name: dev.lions.dev
