---
# =============================================================================
# LIONS Infrastructure - Inventaire Environnement de Développement
# =============================================================================
# Description: Configuration des hôtes pour l'environnement de développement
# Auteur: Équipe LIONS Infrastructure
# Date: 2025-05-24
# Version: 2.0.0
# =============================================================================

all:
  children:
    # Groupe des serveurs VPS
    vps:
      hosts:
        contabo-vps:
          ansible_host: 176.57.150.2
          ansible_port: 225  # Port SSH non-standard pour sécurité
          ansible_user: lions-admin  # Utilisateur non-root avec privilèges sudo
          ansible_python_interpreter: /usr/bin/python3
          ansible_connection: local

    # Groupe des nœuds Kubernetes
    kubernetes:
      children:
        # Nœuds serveur K3s (contrôle plane)
        k3s_server:
          hosts:
            contabo-vps:
              ansible_host: 176.57.150.2
              ansible_port: 225
              ansible_connection: local
              k3s_role: server
              k3s_server_id: 1

        # Nœuds agent K3s (worker nodes)
        k3s_agent:
          hosts:
            # Ajouter des nœuds agent ici pour la haute disponibilité
            # Exemple:
            # contabo-vps2:
            #   ansible_host: 176.57.150.3
            #   ansible_port: 225
            #   ansible_user: lions-admin
            #   ansible_python_interpreter: /usr/bin/python3
            #   k3s_role: agent
            #   k3s_agent_id: 1
            #   k3s_server_url: https://176.57.150.2:6443

    # Groupe des serveurs de bases de données
    databases:
      hosts:
        contabo-vps:
          ansible_host: 176.57.150.2
          ansible_port: 225
          ansible_connection: local

    # Groupe des serveurs de monitoring
    monitoring:
      hosts:
        contabo-vps:
          ansible_host: 176.57.150.2
          ansible_port: 225
          ansible_connection: local

  # Variables globales pour tous les hôtes
  vars:
    # Configuration d'authentification
    ansible_user: lions-admin  # Utilisateur dédié avec privilèges limités
    ansible_become: yes  # Élévation de privilèges via sudo
    ansible_become_method: sudo

    # Utilisation de vault pour les informations sensibles
    ansible_ssh_private_key_file: "{{ lookup('hashi_vault', 'secret=kv/data/lions/ssh:private_key') }}"
    ansible_become_pass: "{{ lookup('hashi_vault', 'secret=kv/data/lions/ssh:sudo_password') }}"

    # Variables d'environnement
    environment: development
    domain_name: dev.lions.dev

    # Configuration de sécurité
    ssh_allow_agent_forwarding: false
    ssh_allow_tcp_forwarding: false
    fail2ban_enabled: true
    ufw_enabled: true
