---
# Titre: Configuration Kustomize pour l'environnement de staging
# Description: Définit la configuration Kustomize pour l'environnement de staging
# Auteur: Équipe LIONS Infrastructure
# Date: 2025-05-07
# Version: 1.0.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Ressources de base à inclure
resources:
  - namespace.yaml
  - ../../base/network-policies
  - ../../base/rbac
  - ../../base/resource-quotas
  - ../../base/cert-manager

# Patches spécifiques à l'environnement de staging
patches:
  - path: patches/resource-quotas-patch.yaml

# Configuration des namespaces
namespace: staging

# Labels communs à ajouter à toutes les ressources
commonLabels:
  environment: staging
  managed-by: kustomize

# Annotations communes à ajouter à toutes les ressources
commonAnnotations:
  environment.lions.dev/description: "Environnement de staging pour les applications LIONS"
  environment.lions.dev/contact: "staging-team@lions.dev"
  environment.lions.dev/documentation: "https://docs.lions.dev/environments/staging"

# Configuration des remplacements
replacements:
  - source:
      kind: Namespace
      name: staging
      fieldPath: metadata.name
    targets:
      - select:
          kind: "*"
        fieldPaths:
          - metadata.namespace
        options:
          create: true
