---
# Titre: Configuration Kustomize pour l'environnement de développement
# Description: Définit la configuration Kustomize pour l'environnement de développement
# Auteur: Équipe LIONS Infrastructure
# Date: 2025-05-07
# Version: 1.0.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Ressources de base à inclure
resources:
  - namespace.yaml
  - ../../base/network-policies
  - ../../base/rbac
  - ../../base/resource-quotas

# Patches spécifiques à l'environnement de développement
patches:
  - path: patches/resource-quotas-patch.yaml
  - path: patches/network-policies-patch.yaml

# Configuration des namespaces
namespace: development

# Labels communs à ajouter à toutes les ressources
labels:
  environment: development
  managed-by: kustomize

# Annotations communes à ajouter à toutes les ressources
commonAnnotations:
  environment.lions.dev/description: "Environnement de développement pour les applications LIONS"
  environment.lions.dev/contact: "dev-team@lions.dev"
  environment.lions.dev/documentation: "https://docs.lions.dev/environments/development"

# Configuration des remplacements
replacements:
  - source:
      kind: Namespace
      name: development
      fieldPath: metadata.name
    targets:
      - select:
          kind: "*"
        fieldPaths:
          - metadata.namespace
        options:
          create: true
