---
all:
  children:
    kubernetes:
      children:
        control_plane:
          hosts:
            kube-master-01:
              ansible_host: 192.168.1.101
            kube-master-02:
              ansible_host: 192.168.1.102
            kube-master-03:
              ansible_host: 192.168.1.103
        workers:
          hosts:
            kube-worker-01:
              ansible_host: 192.168.1.111
            kube-worker-02:
              ansible_host: 192.168.1.112
            kube-worker-03:
              ansible_host: 192.168.1.113
            kube-worker-04:
              ansible_host: 192.168.1.114
    databases:
      hosts:
        db-server-01:
          ansible_host: 192.168.1.201
        db-server-02:
          ansible_host: 192.168.1.202
    monitoring:
      hosts:
        monitoring-server-01:
          ansible_host: 192.168.1.301
        monitoring-server-02:
          ansible_host: 192.168.1.302
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: /etc/ansible/ssh_keys/ansible_id_rsa
    ansible_become: yes
    environment: production
    domain_name: lions.dev