# Titre: Patch de quotas de ressources pour l'environnement de développement
# Description: Ajuste les quotas de ressources pour l'environnement de développement
# Auteur: Équipe LIONS Infrastructure
# Date: 2025-05-08
# Version: 1.0.0

apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    requests.cpu: '5'
    requests.memory: 10Gi
    limits.cpu: '6'
    limits.memory: 12Gi
    pods: '30'
    services: '20'
    persistentvolumeclaims: '10'
    secrets: '20'
    configmaps: '20'
