# Titre: Liaison de rôle pour les développeurs
# Description: Définit la liaison de rôle pour les développeurs dans l'infrastructure LIONS
# Auteur: Équipe LIONS Infrastructure
# Date: 2025-05-08
# Version: 1.0.0

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lions-developer-binding
  namespace: development
  labels:
    app.kubernetes.io/part-of: lions-infrastructure
subjects:
- kind: Group
  name: lions-developers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: lions-developer
  apiGroup: rbac.authorization.k8s.io