# Titre: Liaison de rôle pour les opérateurs
# Description: Définit la liaison de rôle pour les opérateurs dans l'infrastructure LIONS
# Auteur: Équipe LIONS Infrastructure
# Date: 2025-05-08
# Version: 1.0.0

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lions-operator-binding
  labels:
    app.kubernetes.io/part-of: lions-infrastructure
subjects:
- kind: Group
  name: lions-operators
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: lions-operator
  apiGroup: rbac.authorization.k8s.io