---
# Titre: Configuration RBAC
# Description: Définit les liaisons de rôles pour l'infrastructure LIONS
# Auteur: Équipe LIONS Infrastructure
# Date: 2025-05-08
# Version: 1.0.0
---
# Liaison de rôle pour les développeurs dans l'environnement de développement
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lions-developer-binding
  namespace: development
  labels:
    app.kubernetes.io/part-of: lions-infrastructure
subjects:
- kind: Group
  name: lions-developers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: lions-developer
  apiGroup: rbac.authorization.k8s.io
---
# Liaison de rôle pour les opérateurs dans tous les environnements
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lions-operator-binding
  labels:
    app.kubernetes.io/part-of: lions-infrastructure
subjects:
- kind: Group
  name: lions-operators
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: lions-operator
  apiGroup: rbac.authorization.k8s.io
---
# Liaison de rôle pour les administrateurs
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lions-admin-binding
  labels:
    app.kubernetes.io/part-of: lions-infrastructure
subjects:
- kind: Group
  name: lions-admins
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: lions-admin
  apiGroup: rbac.authorization.k8s.io
---
# Liaison de rôle pour le monitoring
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lions-monitoring-binding
  labels:
    app.kubernetes.io/part-of: lions-infrastructure
subjects:
- kind: ServiceAccount
  name: prometheus-operator
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: lions-monitoring
  apiGroup: rbac.authorization.k8s.io
---
# Rôle spécifique pour les applications Quarkus
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: quarkus-app-role
  namespace: default
  labels:
    app.kubernetes.io/part-of: lions-infrastructure
    technology: quarkus
rules:
  # Accès aux secrets et configmaps
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
  # Accès aux services
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch"]
---
# Rôle spécifique pour les applications PrimeFaces
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: primefaces-app-role
  namespace: default
  labels:
    app.kubernetes.io/part-of: lions-infrastructure
    technology: primefaces
rules:
  # Accès aux secrets et configmaps
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
  # Accès aux services
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch"]
---
# Rôle spécifique pour les applications PrimeReact
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: primereact-app-role
  namespace: default
  labels:
    app.kubernetes.io/part-of: lions-infrastructure
    technology: primereact
rules:
  # Accès aux secrets et configmaps
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
  # Accès aux services
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch"]
---
# Rôle spécifique pour le service de notification
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: notification-service-role
  namespace: default
  labels:
    app.kubernetes.io/part-of: lions-infrastructure
    technology: notification-service
rules:
  # Accès aux secrets et configmaps
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
  # Accès aux services
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch"]
  # Accès pour envoyer des notifications
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
