---
# Titre: Configuration RBAC
# Description: Définit les rôles spécifiques aux applications pour l'infrastructure LIONS
# Auteur: Équipe LIONS Infrastructure
# Date: 2025-05-08
# Version: 1.0.0
---
# Rôle spécifique pour les applications Quarkus
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: quarkus-app-role
  namespace: default
  labels:
    app.kubernetes.io/part-of: lions-infrastructure
    technology: quarkus
rules:
  # Accès aux secrets et configmaps
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
  # Accès aux services
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch"]
---
# Rôle spécifique pour les applications PrimeFaces
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: primefaces-app-role
  namespace: default
  labels:
    app.kubernetes.io/part-of: lions-infrastructure
    technology: primefaces
rules:
  # Accès aux secrets et configmaps
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
  # Accès aux services
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch"]
---
# Rôle spécifique pour les applications PrimeReact
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: primereact-app-role
  namespace: default
  labels:
    app.kubernetes.io/part-of: lions-infrastructure
    technology: primereact
rules:
  # Accès aux secrets et configmaps
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
  # Accès aux services
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch"]
---
# Rôle spécifique pour le service de notification
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: notification-service-role
  namespace: default
  labels:
    app.kubernetes.io/part-of: lions-infrastructure
    technology: notification-service
rules:
  # Accès aux secrets et configmaps
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
  # Accès aux services
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch"]
  # Accès pour envoyer des notifications
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
