---
all:
  children:
    kubernetes:
      children:
        control_plane:
          hosts:
            kube-master-01:
              ansible_host: 192.168.2.101
        workers:
          hosts:
            kube-worker-01:
              ansible_host: 192.168.2.111
            kube-worker-02:
              ansible_host: 192.168.2.112
    databases:
      hosts:
        db-server-01:
          ansible_host: 192.168.2.201
    monitoring:
      hosts:
        monitoring-server-01:
          ansible_host: 192.168.2.301
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: /etc/ansible/ssh_keys/ansible_id_rsa
    ansible_become: yes
    environment: staging
    domain_name: staging.lions.dev