---
# Titre: Configuration du monitoring pour Quarkus
# Description: Configure le monitoring pour une application Quarkus
# Auteur: Équipe LIONS Infrastructure
# Date: 2025-05-07
# Version: 1.0.0

- name: Vérification de l'existence de Prometheus Operator
  k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: servicemonitors.monitoring.coreos.com
  register: prometheus_operator_check
  ignore_errors: yes

- name: Création du ServiceMonitor pour Prometheus
  k8s:
    state: present
    src: "{{ temp_dir.path }}/servicemonitor.yml"
  register: servicemonitor_result
  when: 
    - prometheus_operator_check is succeeded
    - prometheus_operator_check.resources | length > 0
    - quarkus_prometheus_scrape | bool

- name: Avertissement si Prometheus Operator n'est pas installé
  debug:
    msg: "AVERTISSEMENT: Prometheus Operator n'est pas installé. Le monitoring automatique ne sera pas configuré."
  when: prometheus_operator_check is failed or prometheus_operator_check.resources | length == 0

- name: Configuration des règles d'alerte pour l'application
  k8s:
    state: present
    definition:
      apiVersion: monitoring.coreos.com/v1
      kind: PrometheusRule
      metadata:
        name: "{{ app_name }}-alerts"
        namespace: "{{ app_namespace }}"
        labels:
          app: "{{ app_name }}"
          prometheus: k8s
          role: alert-rules
      spec:
        groups:
          - name: "{{ app_name }}.rules"
            rules:
              - alert: InstanceDown
                expr: up{job="{{ app_name }}"} == 0
                for: 5m
                labels:
                  severity: critical
                annotations:
                  summary: "Instance {{ app_name }} down"
                  description: "{{ app_name }} instance has been down for more than 5 minutes."
              - alert: HighMemoryUsage
                expr: container_memory_usage_bytes{pod=~"{{ app_name }}.*"} / container_spec_memory_limit_bytes{pod=~"{{ app_name }}.*"} > 0.85
                for: 10m
                labels:
                  severity: warning
                annotations:
                  summary: "High memory usage for {{ app_name }}"
                  description: "{{ app_name }} is using more than 85% of its memory limit for more than 10 minutes."
              - alert: HighCPUUsage
                expr: container_cpu_usage_seconds_total{pod=~"{{ app_name }}.*"} / container_spec_cpu_quota{pod=~"{{ app_name }}.*"} > 0.85
                for: 10m
                labels:
                  severity: warning
                annotations:
                  summary: "High CPU usage for {{ app_name }}"
                  description: "{{ app_name }} is using more than 85% of its CPU limit for more than 10 minutes."
              - alert: HighLatency
                expr: http_server_requests_seconds_max{service="{{ app_name }}"} > 1
                for: 5m
                labels:
                  severity: warning
                annotations:
                  summary: "High latency for {{ app_name }}"
                  description: "{{ app_name }} has high latency (>1s) for more than 5 minutes."
  when: 
    - prometheus_operator_check is succeeded
    - prometheus_operator_check.resources | length > 0
    - quarkus_prometheus_scrape | bool

- name: Configuration de Grafana Dashboard
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ app_name }}-dashboard"
        namespace: monitoring
        labels:
          grafana_dashboard: "1"
      data:
        "{{ app_name }}-dashboard.json": |
          {
            "annotations": {
              "list": [
                {
                  "builtIn": 1,
                  "datasource": "-- Grafana --",
                  "enable": true,
                  "hide": true,
                  "iconColor": "rgba(0, 211, 255, 1)",
                  "name": "Annotations & Alerts",
                  "type": "dashboard"
                }
              ]
            },
            "editable": true,
            "gnetId": null,
            "graphTooltip": 0,
            "id": null,
            "links": [],
            "panels": [
              {
                "aliasColors": {},
                "bars": false,
                "dashLength": 10,
                "dashes": false,
                "datasource": "Prometheus",
                "fill": 1,
                "fillGradient": 0,
                "gridPos": {
                  "h": 8,
                  "w": 12,
                  "x": 0,
                  "y": 0
                },
                "hiddenSeries": false,
                "id": 2,
                "legend": {
                  "avg": false,
                  "current": false,
                  "max": false,
                  "min": false,
                  "show": true,
                  "total": false,
                  "values": false
                },
                "lines": true,
                "linewidth": 1,
                "nullPointMode": "null",
                "options": {
                  "dataLinks": []
                },
                "percentage": false,
                "pointradius": 2,
                "points": false,
                "renderer": "flot",
                "seriesOverrides": [],
                "spaceLength": 10,
                "stack": false,
                "steppedLine": false,
                "targets": [
                  {
                    "expr": "container_memory_usage_bytes{pod=~\"{{ app_name }}.*\"}",
                    "refId": "A"
                  }
                ],
                "thresholds": [],
                "timeFrom": null,
                "timeRegions": [],
                "timeShift": null,
                "title": "Memory Usage",
                "tooltip": {
                  "shared": true,
                  "sort": 0,
                  "value_type": "individual"
                },
                "type": "graph",
                "xaxis": {
                  "buckets": null,
                  "mode": "time",
                  "name": null,
                  "show": true,
                  "values": []
                },
                "yaxes": [
                  {
                    "format": "bytes",
                    "label": null,
                    "logBase": 1,
                    "max": null,
                    "min": null,
                    "show": true
                  },
                  {
                    "format": "short",
                    "label": null,
                    "logBase": 1,
                    "max": null,
                    "min": null,
                    "show": true
                  }
                ],
                "yaxis": {
                  "align": false,
                  "alignLevel": null
                }
              }
            ],
            "schemaVersion": 22,
            "style": "dark",
            "tags": [],
            "templating": {
              "list": []
            },
            "time": {
              "from": "now-6h",
              "to": "now"
            },
            "timepicker": {},
            "timezone": "",
            "title": "{{ app_name }} Dashboard",
            "uid": "{{ app_name }}-dashboard",
            "version": 1
          }
  when: 
    - prometheus_operator_check is succeeded
    - prometheus_operator_check.resources | length > 0
    - quarkus_prometheus_scrape | bool
  ignore_errors: yes