apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app: {{ .Release.Name }}
    spec:
      hostAliases:
      - ip: {{ .Values.hostAlias.ip }}
        hostnames:
        - {{ .Values.hostAlias.hostname | quote }}
      containers:
      - image: {{ .Values.container.registryUri }}/{{ .Release.Name }}:{{ .Values.container.tag }}
        name: {{ .Release.Name }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}
        resources:
          limits:
            memory: {{ .Values.container.memory }}
        volumeMounts:
        - name: {{ .Release.Name }}-data
          mountPath: /{{ .Release.Name }}-data
      volumes:
      - name: {{ .Release.Name }}-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}
        
