---
# =========================================================================
# LIONS INFRASTRUCTURE 5.0 - INVENTAIRE PRODUCTION
# =========================================================================
# Description: Configuration d'inventaire Ansible pour l'environnement de production
# Version: 5.0.0
# Environment: production
# Maintainer: DevOps Team
# Documentation: https://docs.lions.dev/infrastructure/ansible/inventories
# =========================================================================

all:
  children:
    # =====================================================================
    # CLUSTER KUBERNETES - HAUTE DISPONIBILITÉ
    # =====================================================================
    kubernetes_cluster:
      children:
        # -----------------------------------------------------------------
        # NŒUDS DE CONTRÔLE (CONTROL PLANE)
        # Configuration HA avec 3 nœuds maîtres pour la résilience
        # -----------------------------------------------------------------
        k3s_control_plane:
          hosts:
            lions-k3s-master-01:
              ansible_host: "{{ lions_k3s_master_01_ip | default('192.168.1.101') }}"
              k3s_node_role: "master"
              k3s_node_priority: 100
              k3s_etcd_member: true
              k3s_api_server: true
              k3s_scheduler: true
              k3s_controller_manager: true
              metallb_speaker_enabled: true

            lions-k3s-master-02:
              ansible_host: "{{ lions_k3s_master_02_ip | default('192.168.1.102') }}"
              k3s_node_role: "master"
              k3s_node_priority: 90
              k3s_etcd_member: true
              k3s_api_server: true
              k3s_scheduler: true
              k3s_controller_manager: true
              metallb_speaker_enabled: true

            lions-k3s-master-03:
              ansible_host: "{{ lions_k3s_master_03_ip | default('192.168.1.103') }}"
              k3s_node_role: "master"
              k3s_node_priority: 80
              k3s_etcd_member: true
              k3s_api_server: true
              k3s_scheduler: true
              k3s_controller_manager: true
              metallb_speaker_enabled: true

        # -----------------------------------------------------------------
        # NŒUDS DE TRAVAIL (WORKERS)
        # Nœuds dédiés pour l'exécution des charges de travail
        # -----------------------------------------------------------------
        k3s_workers:
          children:
            # Workers génériques pour les applications standard
            k3s_workers_general:
              hosts:
                lions-k3s-worker-01:
                  ansible_host: "{{ lions_k3s_worker_01_ip | default('192.168.1.111') }}"
                  k3s_node_role: "worker"
                  k3s_node_labels:
                    - "workload.lions.dev/type=general"
                    - "workload.lions.dev/tier=standard"
                  k3s_node_taints: []

                lions-k3s-worker-02:
                  ansible_host: "{{ lions_k3s_worker_02_ip | default('192.168.1.112') }}"
                  k3s_node_role: "worker"
                  k3s_node_labels:
                    - "workload.lions.dev/type=general"
                    - "workload.lions.dev/tier=standard"
                  k3s_node_taints: []

            # Workers spécialisés pour les bases de données
            k3s_workers_database:
              hosts:
                lions-k3s-worker-db-01:
                  ansible_host: "{{ lions_k3s_worker_db_01_ip | default('192.168.1.121') }}"
                  k3s_node_role: "worker"
                  k3s_node_labels:
                    - "workload.lions.dev/type=database"
                    - "workload.lions.dev/tier=performance"
                    - "storage.lions.dev/type=ssd"
                  k3s_node_taints:
                    - "workload.lions.dev/database=true:NoSchedule"

                lions-k3s-worker-db-02:
                  ansible_host: "{{ lions_k3s_worker_db_02_ip | default('192.168.1.122') }}"
                  k3s_node_role: "worker"
                  k3s_node_labels:
                    - "workload.lions.dev/type=database"
                    - "workload.lions.dev/tier=performance"
                    - "storage.lions.dev/type=ssd"
                  k3s_node_taints:
                    - "workload.lions.dev/database=true:NoSchedule"

            # Workers spécialisés pour l'IA (Ollama)
            k3s_workers_ai:
              hosts:
                lions-k3s-worker-ai-01:
                  ansible_host: "{{ lions_k3s_worker_ai_01_ip | default('192.168.1.131') }}"
                  k3s_node_role: "worker"
                  k3s_node_labels:
                    - "workload.lions.dev/type=ai"
                    - "workload.lions.dev/tier=compute"
                    - "hardware.lions.dev/gpu=true"
                  k3s_node_taints:
                    - "workload.lions.dev/ai=true:NoSchedule"
                  gpu_enabled: true
                  gpu_driver_version: "535.129.03"

    # =====================================================================
    # INFRASTRUCTURE EXTERNE
    # =====================================================================
    infrastructure:
      children:
        # -----------------------------------------------------------------
        # SERVEURS DE BASE DE DONNÉES EXTERNES
        # Pour les bases de données critiques hors Kubernetes
        # -----------------------------------------------------------------
        external_databases:
          hosts:
            lions-db-primary-01:
              ansible_host: "{{ lions_db_primary_01_ip | default('192.168.1.201') }}"
              database_role: "primary"
              database_type: "postgresql"
              database_version: "15.4"
              replication_enabled: true
              backup_enabled: true

            lions-db-replica-01:
              ansible_host: "{{ lions_db_replica_01_ip | default('192.168.1.202') }}"
              database_role: "replica"
              database_type: "postgresql"
              database_version: "15.4"
              replication_source: "lions-db-primary-01"
              readonly_mode: true

        # -----------------------------------------------------------------
        # SERVEURS DE MONITORING EXTERNES
        # Pour le monitoring centralisé et les métriques critiques
        # -----------------------------------------------------------------
        external_monitoring:
          hosts:
            lions-monitoring-01:
              ansible_host: "{{ lions_monitoring_01_ip | default('192.168.1.301') }}"
              monitoring_role: "primary"
              prometheus_external: true
              grafana_external: true
              alertmanager_external: true

            lions-monitoring-02:
              ansible_host: "{{ lions_monitoring_02_ip | default('192.168.1.302') }}"
              monitoring_role: "secondary"
              prometheus_external: true
              grafana_external: false
              alertmanager_external: true

        # -----------------------------------------------------------------
        # SERVEURS DE STOCKAGE EXTERNES
        # Pour le stockage distribué et les sauvegardes
        # -----------------------------------------------------------------
        external_storage:
          hosts:
            lions-storage-01:
              ansible_host: "{{ lions_storage_01_ip | default('192.168.1.401') }}"
              storage_role: "primary"
              storage_type: "ceph"
              storage_capacity: "10TB"

            lions-storage-02:
              ansible_host: "{{ lions_storage_02_ip | default('192.168.1.402') }}"
              storage_role: "replica"
              storage_type: "ceph"
              storage_capacity: "10TB"

        # -----------------------------------------------------------------
        # SERVEURS DE SÉCURITÉ
        # Pour Vault et les services de sécurité critiques
        # -----------------------------------------------------------------
        security_infrastructure:
          hosts:
            lions-vault-01:
              ansible_host: "{{ lions_vault_01_ip | default('192.168.1.501') }}"
              vault_role: "active"
              vault_ha_enabled: true
              vault_auto_unseal: true

            lions-vault-02:
              ansible_host: "{{ lions_vault_02_ip | default('192.168.1.502') }}"
              vault_role: "standby"
              vault_ha_enabled: true
              vault_auto_unseal: true

    # =====================================================================
    # GROUPES FONCTIONNELS
    # =====================================================================
    functional_groups:
      children:
        # -----------------------------------------------------------------
        # TOUS LES NŒUDS KUBERNETES
        # -----------------------------------------------------------------
        k3s_cluster:
          children:
            - k3s_control_plane
            - k3s_workers

        # -----------------------------------------------------------------
        # TOUS LES SERVICES DE BASE DE DONNÉES
        # -----------------------------------------------------------------
        all_databases:
          children:
            - external_databases
            - k3s_workers_database

        # -----------------------------------------------------------------
        # TOUS LES SERVICES DE MONITORING
        # -----------------------------------------------------------------
        all_monitoring:
          children:
            - external_monitoring

        # -----------------------------------------------------------------
        # TOUS LES SERVICES DE SÉCURITÉ
        # -----------------------------------------------------------------
        all_security:
          children:
            - security_infrastructure

  # =======================================================================
  # VARIABLES GLOBALES DE PRODUCTION
  # =======================================================================
  vars:
    # -------------------------------------------------------------------
    # CONFIGURATION ENVIRONNEMENT
    # -------------------------------------------------------------------
    lions_environment: "production"
    lions_deployment_mode: "ha"
    lions_config_version: "5.0.0"

    # -------------------------------------------------------------------
    # CONFIGURATION ANSIBLE
    # -------------------------------------------------------------------
    ansible_user: "{{ lions_ansible_user | default('lions-admin') }}"
    ansible_ssh_private_key_file: "{{ lions_ssh_private_key | default('/etc/lions/ssh/production_key') }}"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    ansible_become: true
    ansible_become_method: "sudo"
    ansible_become_user: "root"
    ansible_python_interpreter: "/usr/bin/python3"

    # -------------------------------------------------------------------
    # CONFIGURATION RÉSEAU
    # -------------------------------------------------------------------
    lions_domain_base: "{{ lions_dns_domain_base | default('lions.dev') }}"
    lions_domain_full: "{{ lions_dns_full_domain | default('prod.lions.dev') }}"
    lions_network_subnet: "{{ lions_network_subnet | default('192.168.1.0/24') }}"
    lions_network_gateway: "{{ lions_network_gateway | default('192.168.1.1') }}"
    lions_dns_servers:
      - "{{ lions_dns_primary | default('1.1.1.1') }}"
      - "{{ lions_dns_secondary | default('8.8.8.8') }}"

    # -------------------------------------------------------------------
    # CONFIGURATION KUBERNETES
    # -------------------------------------------------------------------
    k3s_version: "{{ lions_k8s_version | default('v1.30.2+k3s1') }}"
    k3s_cluster_cidr: "{{ lions_k8s_cluster_cidr | default('10.42.0.0/16') }}"
    k3s_service_cidr: "{{ lions_k8s_service_cidr | default('10.43.0.0/16') }}"
    k3s_cluster_dns: "{{ lions_k8s_dns_domain | default('cluster.local') }}"
    k3s_token: "{{ vault_k3s_cluster_token }}"
    k3s_datastore_endpoint: "{{ vault_k3s_datastore_endpoint }}"

    # Configuration haute disponibilité
    k3s_ha_enabled: true
    k3s_etcd_expose_metrics: true
    k3s_disable_components:
      - "traefik"  # Nous utilisons notre propre configuration Traefik

    # Configuration MetalLB pour le LoadBalancer
    metallb_enabled: true
    metallb_ip_range: "{{ lions_metallb_ip_range | default('192.168.1.240-192.168.1.250') }}"

    # -------------------------------------------------------------------
    # CONFIGURATION SÉCURITÉ
    # -------------------------------------------------------------------
    lions_security_hardening: true
    lions_firewall_enabled: true
    lions_fail2ban_enabled: true
    lions_automatic_updates: false  # Contrôlé manuellement en production

    # Configuration TLS/SSL
    tls_cert_email: "{{ lions_security_tls_email | default('admin@lions.dev') }}"
    tls_staging: false  # Production utilise les vrais certificats

    # -------------------------------------------------------------------
    # CONFIGURATION MONITORING
    # -------------------------------------------------------------------
    monitoring_enabled: true
    prometheus_retention: "{{ lions_prometheus_retention | default('90d') }}"
    grafana_admin_user: "{{ vault_grafana_admin_user }}"
    grafana_admin_password: "{{ vault_grafana_admin_password }}"

    # -------------------------------------------------------------------
    # CONFIGURATION BACKUP
    # -------------------------------------------------------------------
    backup_enabled: true
    backup_retention_days: "{{ lions_backup_retention_days | default('90') }}"
    backup_schedule: "{{ lions_backup_schedule | default('0 2 * * *') }}"
    backup_external_enabled: true
    backup_encryption_enabled: true

    # -------------------------------------------------------------------
    # CONFIGURATION PERFORMANCE
    # -------------------------------------------------------------------
    max_pods_per_node: 110
    max_user_namespaces: 10000
    system_reserved_cpu: "200m"
    system_reserved_memory: "512Mi"

    # Limites de ressources par défaut
    default_cpu_request: "{{ lions_resources_medium_cpu_request | default('200m') }}"
    default_cpu_limit: "{{ lions_resources_medium_cpu_limit | default('1000m') }}"
    default_memory_request: "{{ lions_resources_medium_memory_request | default('512Mi') }}"
    default_memory_limit: "{{ lions_resources_medium_memory_limit | default('2Gi') }}"

    # -------------------------------------------------------------------
    # CONFIGURATION SPÉCIFIQUE PRODUCTION
    # -------------------------------------------------------------------
    # Timeouts plus élevés pour la production
    ansible_timeout: 600
    k3s_install_timeout: 1800
    application_deployment_timeout: 3600

    # Configuration de la maintenance
    maintenance_window_start: "02:00"
    maintenance_window_end: "04:00"
    maintenance_timezone: "UTC"

    # -------------------------------------------------------------------
    # INTÉGRATION VAULT
    # -------------------------------------------------------------------
    vault_integration_enabled: true
    vault_addr: "{{ lions_vault_addr | default('https://vault.prod.lions.dev') }}"
    vault_namespace: "{{ lions_vault_namespace | default('production') }}"
    vault_auth_method: "kubernetes"

    # -------------------------------------------------------------------
    # CONFIGURATION LOGGING
    # -------------------------------------------------------------------
    log_level: "WARN"  # Moins verbeux en production
    audit_log_enabled: true
    audit_log_retention: "365d"  # 1 an pour la conformité

    # Centralisation des logs
    centralized_logging: true
    syslog_server: "{{ lions_syslog_server | default('logs.prod.lions.dev') }}"

    # -------------------------------------------------------------------
    # TAGS DE RESSOURCES
    # -------------------------------------------------------------------
    resource_tags:
      environment: "production"
      project: "lions-infrastructure"
      version: "5.0.0"
      maintainer: "devops@lions.dev"
      cost_center: "infrastructure"
      backup_policy: "daily"
      monitoring: "enabled"