---
# Titre: Préparation des ressources pour PrimeFaces
# Description: Prépare les ressources nécessaires pour déployer une application PrimeFaces
# Auteur: Équipe LIONS Infrastructure
# Date: 2025-05-07
# Version: 1.0.0

- name: Création du répertoire temporaire pour les templates
  tempfile:
    state: directory
    suffix: primefaces-deploy
  register: temp_dir
  changed_when: false

- name: Génération des fichiers de configuration Kubernetes
  template:
    src: "{{ item.src }}"
    dest: "{{ temp_dir.path }}/{{ item.dest }}"
  loop:
    - { src: "deployment.yml.j2", dest: "deployment.yml" }
    - { src: "service.yml.j2", dest: "service.yml" }
    - { src: "ingress.yml.j2", dest: "ingress.yml" }
    - { src: "configmap.yml.j2", dest: "configmap.yml" }
    - { src: "serviceaccount.yml.j2", dest: "serviceaccount.yml" }
    - { src: "servicemonitor.yml.j2", dest: "servicemonitor.yml" }
    - { src: "persistentvolumeclaim.yml.j2", dest: "persistentvolumeclaim.yml" }
  register: templates_generated

- name: Vérification des fichiers générés
  stat:
    path: "{{ temp_dir.path }}/{{ item }}"
  loop:
    - "deployment.yml"
    - "service.yml"
    - "ingress.yml"
    - "configmap.yml"
    - "serviceaccount.yml"
    - "servicemonitor.yml"
    - "persistentvolumeclaim.yml"
  register: files_check
  failed_when: not item.stat.exists

- name: Création du compte de service
  k8s:
    state: present
    src: "{{ temp_dir.path }}/serviceaccount.yml"
  register: serviceaccount_result

- name: Création du ConfigMap pour la configuration de l'application
  k8s:
    state: present
    src: "{{ temp_dir.path }}/configmap.yml"
  register: configmap_result

- name: Création du PersistentVolumeClaim pour les données de l'application
  k8s:
    state: present
    src: "{{ temp_dir.path }}/persistentvolumeclaim.yml"
  register: pvc_result
  when: primefaces_persistent_storage | bool

- name: Vérification de l'existence des secrets nécessaires
  k8s_info:
    api_version: v1
    kind: Secret
    namespace: "{{ app_namespace }}"
    name: "{{ app_name }}-secrets"
  register: secrets_info
  ignore_errors: yes

- name: Avertissement si les secrets n'existent pas
  debug:
    msg: "AVERTISSEMENT: Les secrets pour l'application {{ app_name }} n'existent pas. Utilisez kubectl pour créer les secrets nécessaires."
  when: secrets_info is failed or secrets_info.resources | length == 0

- name: Préparation des ressources spécifiques à PrimeFaces
  debug:
    msg: "Préparation des ressources spécifiques à PrimeFaces"

- name: Vérification de l'existence du serveur de base de données
  k8s_info:
    api_version: v1
    kind: Service
    namespace: "{{ app_namespace }}"
    name: "{{ primefaces_database_service | default(app_name + '-db') }}"
  register: db_service_info
  ignore_errors: yes

- name: Avertissement si le serveur de base de données n'existe pas
  debug:
    msg: "AVERTISSEMENT: Le serveur de base de données n'existe pas. L'application PrimeFaces pourrait ne pas fonctionner correctement."
  when: db_service_info is failed or db_service_info.resources | length == 0