---
# Titre: Tâches pour le déploiement de MongoDB
# Description: Déploie MongoDB sur Kubernetes
# Auteur: Équipe LIONS Infrastructure
# Date: 2025-05-08
# Version: 1.0.0

- name: Vérification des prérequis pour MongoDB
  include_tasks: prerequisites.yml

- name: Préparation des ressources Kubernetes
  include_tasks: prepare.yml

- name: Déploiement de MongoDB
  include_tasks: deploy.yml

- name: Configuration du monitoring pour MongoDB
  include_tasks: monitoring.yml

- name: Validation post-déploiement
  include_tasks: validate.yml