---
# Titre: Configuration du monitoring pour MongoDB
# Description: Configure le monitoring pour MongoDB avec Prometheus
# Auteur: Équipe LIONS Infrastructure
# Date: 2025-05-08
# Version: 1.0.0

- name: Vérification de l'existence de Prometheus Operator
  k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: servicemonitors.monitoring.coreos.com
  register: prometheus_operator_check
  ignore_errors: yes

- name: Avertissement si Prometheus Operator n'est pas installé
  debug:
    msg: "AVERTISSEMENT: Prometheus Operator n'est pas installé. Le monitoring ne sera pas configuré."
  when: prometheus_operator_check is failed or prometheus_operator_check.resources | length == 0

- name: Déploiement du ServiceMonitor pour MongoDB
  k8s:
    state: present
    src: "{{ temp_dir.path }}/servicemonitor.yml"
  register: servicemonitor_result
  when: prometheus_operator_check is succeeded and prometheus_operator_check.resources | length > 0 and mongodb_prometheus_scrape | default(true) | bool

- name: Vérification de l'existence du ServiceMonitor
  k8s_info:
    api_version: monitoring.coreos.com/v1
    kind: ServiceMonitor
    namespace: "{{ app_namespace }}"
    name: "{{ app_name }}"
  register: servicemonitor_check
  ignore_errors: yes
  when: prometheus_operator_check is succeeded and prometheus_operator_check.resources | length > 0 and mongodb_prometheus_scrape | default(true) | bool

- name: Avertissement si le ServiceMonitor n'a pas été créé
  debug:
    msg: "AVERTISSEMENT: Le ServiceMonitor pour MongoDB n'a pas été créé. Vérifiez les logs pour plus d'informations."
  when: prometheus_operator_check is succeeded and prometheus_operator_check.resources | length > 0 and mongodb_prometheus_scrape | default(true) | bool and (servicemonitor_check is failed or servicemonitor_check.resources | length == 0)

- name: Vérification de l'existence de Grafana
  k8s_info:
    api_version: v1
    kind: Service
    namespace: monitoring
    name: grafana
  register: grafana_check
  ignore_errors: yes

- name: Avertissement si Grafana n'est pas installé
  debug:
    msg: "AVERTISSEMENT: Grafana n'est pas installé. Les dashboards ne seront pas configurés."
  when: grafana_check is failed or grafana_check.resources | length == 0

- name: Création du ConfigMap pour le dashboard MongoDB
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ app_name }}-dashboard"
        namespace: monitoring
        labels:
          app: "{{ app_name }}"
          grafana_dashboard: "1"
      data:
        mongodb-dashboard.json: |
          {
            "annotations": {
              "list": []
            },
            "editable": true,
            "fiscalYearStartMonth": 0,
            "graphTooltip": 0,
            "id": null,
            "links": [],
            "liveNow": false,
            "panels": [
              {
                "datasource": {
                  "type": "prometheus",
                  "uid": "prometheus"
                },
                "fieldConfig": {
                  "defaults": {
                    "color": {
                      "mode": "palette-classic"
                    },
                    "custom": {
                      "axisCenteredZero": false,
                      "axisColorMode": "text",
                      "axisLabel": "",
                      "axisPlacement": "auto",
                      "barAlignment": 0,
                      "drawStyle": "line",
                      "fillOpacity": 10,
                      "gradientMode": "none",
                      "hideFrom": {
                        "legend": false,
                        "tooltip": false,
                        "viz": false
                      },
                      "lineInterpolation": "linear",
                      "lineWidth": 1,
                      "pointSize": 5,
                      "scaleDistribution": {
                        "type": "linear"
                      },
                      "showPoints": "never",
                      "spanNulls": false,
                      "stacking": {
                        "group": "A",
                        "mode": "none"
                      },
                      "thresholdsStyle": {
                        "mode": "off"
                      }
                    },
                    "mappings": [],
                    "thresholds": {
                      "mode": "absolute",
                      "steps": [
                        {
                          "color": "green",
                          "value": null
                        },
                        {
                          "color": "red",
                          "value": 80
                        }
                      ]
                    },
                    "unit": "short"
                  },
                  "overrides": []
                },
                "gridPos": {
                  "h": 8,
                  "w": 12,
                  "x": 0,
                  "y": 0
                },
                "id": 1,
                "options": {
                  "legend": {
                    "calcs": [],
                    "displayMode": "list",
                    "placement": "bottom",
                    "showLegend": true
                  },
                  "tooltip": {
                    "mode": "single",
                    "sort": "none"
                  }
                },
                "targets": [
                  {
                    "datasource": {
                      "type": "prometheus",
                      "uid": "prometheus"
                    },
                    "expr": "mongodb_connections{instance=~\"$instance\"}",
                    "refId": "A"
                  }
                ],
                "title": "MongoDB Connections",
                "type": "timeseries"
              }
            ],
            "refresh": "",
            "schemaVersion": 38,
            "style": "dark",
            "tags": ["mongodb"],
            "templating": {
              "list": [
                {
                  "current": {
                    "selected": false,
                    "text": "All",
                    "value": "$__all"
                  },
                  "datasource": {
                    "type": "prometheus",
                    "uid": "prometheus"
                  },
                  "definition": "label_values(mongodb_connections, instance)",
                  "hide": 0,
                  "includeAll": true,
                  "label": "Instance",
                  "multi": false,
                  "name": "instance",
                  "options": [],
                  "query": {
                    "query": "label_values(mongodb_connections, instance)",
                    "refId": "StandardVariableQuery"
                  },
                  "refresh": 1,
                  "regex": "",
                  "skipUrlSync": false,
                  "sort": 0,
                  "type": "query"
                }
              ]
            },
            "time": {
              "from": "now-6h",
              "to": "now"
            },
            "timepicker": {},
            "timezone": "",
            "title": "MongoDB Overview",
            "uid": "mongodb-overview",
            "version": 1,
            "weekStart": ""
          }
  register: dashboard_result
  ignore_errors: yes
  when: grafana_check is succeeded and grafana_check.resources | length > 0

- name: Avertissement si le dashboard n'a pas été créé
  debug:
    msg: "AVERTISSEMENT: Le dashboard Grafana pour MongoDB n'a pas été créé. Vérifiez les logs pour plus d'informations."
  when: grafana_check is succeeded and grafana_check.resources | length > 0 and dashboard_result is failed