---
# Titre: Validation post-déploiement pour MongoDB
# Description: Effectue des validations après le déploiement de MongoDB
# Auteur: Équipe LIONS Infrastructure
# Date: 2025-05-08
# Version: 1.0.0

- name: Vérification de l'état des pods MongoDB
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ app_namespace }}"
    label_selectors:
      - "app={{ app_name }}"
  register: pods_status
  until: pods_status.resources | length > 0 and pods_status.resources | map(attribute='status.phase') | list | unique | first == "Running"
  retries: 10
  delay: 10

- name: Vérification de l'état du service MongoDB
  k8s_info:
    api_version: v1
    kind: Service
    namespace: "{{ app_namespace }}"
    name: "{{ app_name }}"
  register: service_status
  failed_when: service_status.resources | length == 0

- name: Vérification de la connectivité MongoDB
  shell: "kubectl exec -n {{ app_namespace }} {{ pods_status.resources[0].metadata.name }} -- mongosh --quiet --eval 'db.runCommand({ ping: 1 })'"
  register: mongo_ping
  ignore_errors: yes
  changed_when: false

- name: Affichage du résultat de la connectivité
  debug:
    msg: "Connectivité MongoDB: {{ 'OK' if mongo_ping is succeeded else 'ÉCHEC' }}"

- name: Vérification des métriques Prometheus (si activé)
  shell: "kubectl exec -n {{ app_namespace }} {{ pods_status.resources[0].metadata.name }} -- curl -s http://localhost:{{ mongodb_prometheus_port | default(9216) }}{{ mongodb_prometheus_path | default('/metrics') }} | head -10"
  register: metrics_check
  ignore_errors: yes
  changed_when: false
  when: mongodb_prometheus_scrape | default(true) | bool

- name: Affichage des métriques Prometheus
  debug:
    msg: "Métriques Prometheus: {{ metrics_check.stdout_lines if metrics_check is succeeded else 'Non disponibles' }}"
  when: mongodb_prometheus_scrape | default(true) | bool

- name: Vérification de la sécurité MongoDB
  shell: "kubectl exec -n {{ app_namespace }} {{ pods_status.resources[0].metadata.name }} -- mongosh --quiet --eval 'db.runCommand({ getCmdLineOpts: 1 })'"
  register: security_check
  ignore_errors: yes
  changed_when: false

- name: Analyse de la configuration de sécurité
  debug:
    msg: "Configuration de sécurité MongoDB: {{ 'OK' if security_check is succeeded and 'security' in security_check.stdout else 'À vérifier' }}"
  when: security_check is succeeded

- name: Vérification des ressources utilisées
  shell: "kubectl top pod -n {{ app_namespace }} {{ pods_status.resources[0].metadata.name }}"
  register: resources_check
  ignore_errors: yes
  changed_when: false

- name: Affichage des ressources utilisées
  debug:
    msg: "Ressources utilisées: {{ resources_check.stdout if resources_check is succeeded else 'Non disponibles' }}"

- name: Résumé du déploiement
  debug:
    msg: |
      =====================================================
      RÉSUMÉ DU DÉPLOIEMENT MONGODB
      =====================================================
      Nom: {{ app_name }}
      Namespace: {{ app_namespace }}
      Environnement: {{ app_environment }}
      Version: {{ mongodb_version | default('latest') }}
      Pods en cours d'exécution: {{ pods_status.resources | length }}
      Service disponible: {{ 'Oui' if service_status.resources | length > 0 else 'Non' }}
      Connectivité: {{ 'OK' if mongo_ping is succeeded else 'ÉCHEC' }}
      Monitoring: {{ 'Activé' if mongodb_prometheus_scrape | default(true) | bool else 'Désactivé' }}
      Replica Set: {{ 'Activé' if mongodb_replica_set_enabled | default(false) | bool else 'Désactivé' }}
      =====================================================
      STATUT FINAL: {{ 'SUCCÈS' if mongo_ping is succeeded and service_status.resources | length > 0 and pods_status.resources | length > 0 else 'ÉCHEC' }}
      =====================================================

- name: Échec si la validation échoue
  fail:
    msg: "La validation du déploiement MongoDB a échoué. Veuillez vérifier les logs pour plus d'informations."
  when: mongo_ping is failed or service_status.resources | length == 0 or pods_status.resources | length == 0