---
# Titre: Configuration d'autoscaling pour Gitea
# Description: Définit les règles d'autoscaling horizontal pour le service Gitea
# Auteur: Équipe LIONS Infrastructure
# Date: 2025-05-16
# Version: 1.0.0

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gitea-hpa
  namespace: gitea-development
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gitea
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 1
          periodSeconds: 15
      selectPolicy: Max