---
# Titre: Configuration d'autoscaling pour PrimeReact
# Description: Définit les règles d'autoscaling horizontal pour les services PrimeReact
# Auteur: Équipe LIONS Infrastructure
# Date: 2025-05-16
# Version: 1.0.0

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: primereact-hpa
  namespace: primereact-development
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: primereact
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 2
          periodSeconds: 15
      selectPolicy: Max