---
all:
  children:
    vps:
      hosts:
        contabo-vps:
          ansible_host: 176.57.150.2
          ansible_port: 225
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
          ansible_connection: local
    kubernetes:
      hosts:
        contabo-vps:
          ansible_host: 176.57.150.2
          ansible_port: 225
          ansible_connection: local
    databases:
      hosts:
        contabo-vps:
          ansible_host: 176.57.150.2
          ansible_port: 225
          ansible_connection: local
    monitoring:
      hosts:
        contabo-vps:
          ansible_host: 176.57.150.2
          ansible_port: 225
          ansible_connection: local
  vars:
    ansible_user: root
    ansible_become: yes
    environment: development
    domain_name: dev.lions.dev
