---
# =========================================================================
# LIONS INFRASTRUCTURE 5.0 - RÔLE SERVICE DE NOTIFICATION
# =========================================================================
# Description: Orchestrateur principal pour le déploiement du service de notification
# Version: 5.0.0
# Maintainer: DevOps Team <devops@lions.dev>
# Documentation: https://docs.lions.dev/infrastructure/services/notification
# =========================================================================

# =========================================================================
# MÉTADONNÉES ET CONFIGURATION
# =========================================================================
- name: "Notification | Initialisation des métadonnées de déploiement"
  set_fact:
    notification_deployment_metadata:
      role_name: "notification-service"
      role_version: "5.0.0"
      deployment_id: "{{ ansible_date_time.epoch }}"
      environment: "{{ lions_environment | default('development') }}"
      namespace: "{{ lions_notification_namespace | default('services') }}"
      started_at: "{{ ansible_date_time.iso8601 }}"
      started_by: "{{ ansible_user_id | default('system') }}"
    notification_deployment_config:
      dry_run: "{{ lions_dry_run | default(false) | bool }}"
      debug_mode: "{{ lions_debug_mode | default(false) | bool }}"
      skip_validation: "{{ notification_skip_validation | default(false) | bool }}"
      force_recreate: "{{ notification_force_recreate | default(false) | bool }}"
  tags:
    - notification
    - metadata
    - always

- name: "Notification | Affichage des informations de déploiement"
  debug:
    msg:
      - "🚀 Démarrage du déploiement du service de notification"
      - "📊 Environnement: {{ notification_deployment_metadata.environment }}"
      - "🏷️  Namespace: {{ notification_deployment_metadata.namespace }}"
      - "🆔 ID de déploiement: {{ notification_deployment_metadata.deployment_id }}"
      - "⏰ Démarré le: {{ notification_deployment_metadata.started_at }}"
      - "👤 Initié par: {{ notification_deployment_metadata.started_by }}"
      - "🔧 Mode debug: {{ notification_deployment_config.debug_mode }}"
      - "🧪 Dry run: {{ notification_deployment_config.dry_run }}"
  when: notification_deployment_config.debug_mode | bool
  tags:
    - notification
    - debug
    - always

# =========================================================================
# GESTION DES ERREURS ET ROLLBACK
# =========================================================================
- name: "Notification | Configuration de la gestion d'erreurs"
  set_fact:
    notification_error_handling:
      max_retries: "{{ notification_max_retries | default(3) }}"
      retry_delay: "{{ notification_retry_delay | default(10) }}"
      rollback_on_failure: "{{ notification_rollback_on_failure | default(true) | bool }}"
      error_log_file: "/tmp/notification-deployment-{{ notification_deployment_metadata.deployment_id }}.log"
  tags:
    - notification
    - error-handling
    - always

# =========================================================================
# VÉRIFICATIONS PRÉALABLES CRITIQUES
# =========================================================================
- name: "Notification | Vérification de l'état de l'environnement"
  block:
    - name: "Notification | Vérification de l'accessibilité du cluster Kubernetes"
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Namespace
        name: "{{ notification_deployment_metadata.namespace }}"
      register: notification_namespace_check
      failed_when: false

    - name: "Notification | Vérification des variables d'environnement critiques"
      assert:
        that:
          - lions_notification_enabled is defined
          - lions_notification_enabled | bool
          - lions_notification_version is defined
          - lions_notification_version | length > 0
          - notification_deployment_metadata.namespace is defined
        fail_msg: "Variables d'environnement du service de notification manquantes ou incorrectes"
        success_msg: "Variables d'environnement du service de notification validées"

  rescue:
    - name: "Notification | Gestion d'erreur - Vérifications préalables"
      fail:
        msg: "❌ Échec des vérifications préalables du service de notification: {{ ansible_failed_result.msg | default('Erreur inconnue') }}"

  tags:
    - notification
    - preflight
    - validation

# =========================================================================
# PHASE 1: PRÉREQUIS ET DÉPENDANCES
# =========================================================================
- name: "Notification | Phase 1 - Vérification des prérequis"
  block:
    - name: "Notification | Inclusion des tâches de prérequis"
      include_tasks: prerequisites.yml
      vars:
        current_phase: "prerequisites"
        phase_description: "Vérification des prérequis système et Kubernetes"

  rescue:
    - name: "Notification | Échec Phase 1 - Prérequis"
      set_fact:
        notification_deployment_failed: true
        notification_failure_phase: "prerequisites"
        notification_failure_reason: "{{ ansible_failed_result.msg | default('Échec des prérequis') }}"

    - name: "Notification | Log d'erreur Phase 1"
      lineinfile:
        path: "{{ notification_error_handling.error_log_file }}"
        line: "[{{ ansible_date_time.iso8601 }}] ERREUR Phase 1 (Prérequis): {{ notification_failure_reason }}"
        create: yes

    - name: "Notification | Arrêt du déploiement - Phase 1"
      fail:
        msg: "❌ Déploiement du service de notification interrompu en Phase 1 (Prérequis): {{ notification_failure_reason }}"

  tags:
    - notification
    - prerequisites
    - phase-1

# =========================================================================
# PHASE 2: PRÉPARATION DES RESSOURCES
# =========================================================================
- name: "Notification | Phase 2 - Préparation des ressources"
  block:
    - name: "Notification | Inclusion des tâches de préparation"
      include_tasks: prepare.yml
      vars:
        current_phase: "preparation"
        phase_description: "Création des ressources Kubernetes de base"

  rescue:
    - name: "Notification | Échec Phase 2 - Préparation"
      set_fact:
        notification_deployment_failed: true
        notification_failure_phase: "preparation"
        notification_failure_reason: "{{ ansible_failed_result.msg | default('Échec de la préparation') }}"

    - name: "Notification | Log d'erreur Phase 2"
      lineinfile:
        path: "{{ notification_error_handling.error_log_file }}"
        line: "[{{ ansible_date_time.iso8601 }}] ERREUR Phase 2 (Préparation): {{ notification_failure_reason }}"
        create: yes

    - name: "Notification | Nettoyage partiel après échec Phase 2"
      include_tasks: cleanup.yml
      vars:
        cleanup_scope: "preparation"
      when: notification_error_handling.rollback_on_failure | bool

    - name: "Notification | Arrêt du déploiement - Phase 2"
      fail:
        msg: "❌ Déploiement du service de notification interrompu en Phase 2 (Préparation): {{ notification_failure_reason }}"

  when: notification_deployment_failed is not defined
  tags:
    - notification
    - preparation
    - phase-2

# =========================================================================
# PHASE 3: DÉPLOIEMENT PRINCIPAL
# =========================================================================
- name: "Notification | Phase 3 - Déploiement principal"
  block:
    - name: "Notification | Inclusion des tâches de déploiement"
      include_tasks: deploy.yml
      vars:
        current_phase: "deployment"
        phase_description: "Déploiement des composants du service de notification"

  rescue:
    - name: "Notification | Échec Phase 3 - Déploiement"
      set_fact:
        notification_deployment_failed: true
        notification_failure_phase: "deployment"
        notification_failure_reason: "{{ ansible_failed_result.msg | default('Échec du déploiement') }}"

    - name: "Notification | Log d'erreur Phase 3"
      lineinfile:
        path: "{{ notification_error_handling.error_log_file }}"
        line: "[{{ ansible_date_time.iso8601 }}] ERREUR Phase 3 (Déploiement): {{ notification_failure_reason }}"
        create: yes

    - name: "Notification | Rollback complet après échec Phase 3"
      include_tasks: rollback.yml
      vars:
        rollback_reason: "Échec du déploiement principal"
      when: notification_error_handling.rollback_on_failure | bool

    - name: "Notification | Arrêt du déploiement - Phase 3"
      fail:
        msg: "❌ Déploiement du service de notification interrompu en Phase 3 (Déploiement): {{ notification_failure_reason }}"

  when: notification_deployment_failed is not defined
  tags:
    - notification
    - deployment
    - phase-3

# =========================================================================
# PHASE 4: CONFIGURATION DU MONITORING
# =========================================================================
- name: "Notification | Phase 4 - Configuration du monitoring"
  block:
    - name: "Notification | Inclusion des tâches de monitoring"
      include_tasks: monitoring.yml
      vars:
        current_phase: "monitoring"
        phase_description: "Configuration des métriques et alertes du service de notification"

  rescue:
    - name: "Notification | Avertissement Phase 4 - Monitoring"
      debug:
        msg:
          - "⚠️  Échec de la configuration du monitoring du service de notification"
          - "ℹ️  Le déploiement principal a réussi, mais les métriques peuvent être indisponibles"
          - "🔍 Erreur: {{ ansible_failed_result.msg | default('Erreur de monitoring inconnue') }}"

    - name: "Notification | Log d'avertissement Phase 4"
      lineinfile:
        path: "{{ notification_error_handling.error_log_file }}"
        line: "[{{ ansible_date_time.iso8601 }}] AVERTISSEMENT Phase 4 (Monitoring): {{ ansible_failed_result.msg | default('Erreur de monitoring') }}"
        create: yes

    - name: "Notification | Marquage du monitoring comme défaillant"
      set_fact:
        notification_monitoring_failed: true

  when:
    - notification_deployment_failed is not defined
    - lions_monitoring_enabled | default(true) | bool
  tags:
    - notification
    - monitoring
    - phase-4

# =========================================================================
# PHASE 5: VALIDATION POST-DÉPLOIEMENT
# =========================================================================
- name: "Notification | Phase 5 - Validation post-déploiement"
  block:
    - name: "Notification | Inclusion des tâches de validation"
      include_tasks: validate.yml
      vars:
        current_phase: "validation"
        phase_description: "Validation de l'état et des fonctionnalités du service de notification"

  rescue:
    - name: "Notification | Échec Phase 5 - Validation"
      set_fact:
        notification_deployment_failed: true
        notification_failure_phase: "validation"
        notification_failure_reason: "{{ ansible_failed_result.msg | default('Échec de la validation') }}"

    - name: "Notification | Log d'erreur Phase 5"
      lineinfile:
        path: "{{ notification_error_handling.error_log_file }}"
        line: "[{{ ansible_date_time.iso8601 }}] ERREUR Phase 5 (Validation): {{ notification_failure_reason }}"
        create: yes

    - name: "Notification | Décision sur le rollback après validation"
      debug:
        msg: "⚠️  Validation échouée mais le service de notification peut être partiellement fonctionnel"

    - name: "Notification | Arrêt avec avertissement - Phase 5"
      fail:
        msg: "⚠️  Déploiement du service de notification terminé avec des erreurs de validation: {{ notification_failure_reason }}"

  when:
    - notification_deployment_failed is not defined
    - not notification_deployment_config.skip_validation | bool
  tags:
    - notification
    - validation
    - phase-5

# =========================================================================
# PHASE 6: CONFIGURATION DE LA SAUVEGARDE
# =========================================================================
- name: "Notification | Phase 6 - Configuration de la sauvegarde"
  block:
    - name: "Notification | Inclusion des tâches de sauvegarde"
      include_tasks: backup.yml
      vars:
        current_phase: "backup"
        phase_description: "Configuration des stratégies de sauvegarde du service de notification"

  rescue:
    - name: "Notification | Avertissement Phase 6 - Sauvegarde"
      debug:
        msg:
          - "⚠️  Échec de la configuration de sauvegarde du service de notification"
          - "ℹ️  Le service de notification fonctionne mais les sauvegardes automatiques sont désactivées"
          - "🔍 Erreur: {{ ansible_failed_result.msg | default('Erreur de sauvegarde inconnue') }}"

    - name: "Notification | Log d'avertissement Phase 6"
      lineinfile:
        path: "{{ notification_error_handling.error_log_file }}"
        line: "[{{ ansible_date_time.iso8601 }}] AVERTISSEMENT Phase 6 (Sauvegarde): {{ ansible_failed_result.msg | default('Erreur de sauvegarde') }}"
        create: yes

    - name: "Notification | Marquage de la sauvegarde comme défaillante"
      set_fact:
        notification_backup_failed: true

  when:
    - notification_deployment_failed is not defined
    - lions_backup_enabled | default(true) | bool
    - lions_notification_backup_enabled | default(true) | bool
  tags:
    - notification
    - backup
    - phase-6

# =========================================================================
# FINALISATION ET RAPPORT DE DÉPLOIEMENT
# =========================================================================
- name: "Notification | Génération du rapport de déploiement"
  set_fact:
    notification_deployment_report:
      status: "{{ 'FAILED' if notification_deployment_failed | default(false) else 'SUCCESS' }}"
      environment: "{{ notification_deployment_metadata.environment }}"
      namespace: "{{ notification_deployment_metadata.namespace }}"
      deployment_id: "{{ notification_deployment_metadata.deployment_id }}"
      started_at: "{{ notification_deployment_metadata.started_at }}"
      completed_at: "{{ ansible_date_time.iso8601 }}"
      duration: "{{ (ansible_date_time.epoch | int) - (notification_deployment_metadata.deployment_id | int) }}"
      failed_phase: "{{ notification_failure_phase | default('N/A') }}"
      failure_reason: "{{ notification_failure_reason | default('N/A') }}"
      monitoring_status: "{{ 'FAILED' if notification_monitoring_failed | default(false) else 'OK' }}"
      backup_status: "{{ 'FAILED' if notification_backup_failed | default(false) else 'OK' }}"
      notification_version: "{{ lions_notification_version }}"
      notification_service_name: "{{ lions_notification_service_name | default('notification-service') }}"
      notification_endpoint: "{{ lions_notification_service_name | default('notification-service') }}.{{ notification_deployment_metadata.namespace }}.svc.cluster.local:{{ lions_notification_port | default(8080) }}"
  tags:
    - notification
    - report
    - always

- name: "Notification | Affichage du rapport de déploiement"
  debug:
    msg:
      - "=============================================="
      - "📊 RAPPORT DE DÉPLOIEMENT DU SERVICE DE NOTIFICATION"
      - "=============================================="
      - "📈 Statut: {{ notification_deployment_report.status }}"
      - "🌍 Environnement: {{ notification_deployment_report.environment }}"
      - "🏷️  Namespace: {{ notification_deployment_report.namespace }}"
      - "🆔 ID de déploiement: {{ notification_deployment_report.deployment_id }}"
      - "⏰ Durée: {{ notification_deployment_report.duration }}s"
      - "📱 Version du service: {{ notification_deployment_report.notification_version }}"
      - "🔗 Point de connexion: {{ notification_deployment_report.notification_endpoint }}"
      - "📊 Monitoring: {{ notification_deployment_report.monitoring_status }}"
      - "💾 Sauvegarde: {{ notification_deployment_report.backup_status }}"
      - "{{ '❌ Phase d\'échec: ' + notification_deployment_report.failed_phase if notification_deployment_report.status == 'FAILED' else '✅ Déploiement réussi' }}"
      - "{{ '🔍 Raison: ' + notification_deployment_report.failure_reason if notification_deployment_report.status == 'FAILED' else '' }}"
      - "=============================================="
  tags:
    - notification
    - report
    - always

- name: "Notification | Sauvegarde du rapport de déploiement"
  copy:
    content: "{{ notification_deployment_report | to_nice_json }}"
    dest: "/tmp/notification-deployment-report-{{ notification_deployment_metadata.deployment_id }}.json"
  delegate_to: localhost
  tags:
    - notification
    - report

# =========================================================================
# NETTOYAGE ET FINALISATION
# =========================================================================
- name: "Notification | Nettoyage des fichiers temporaires"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ notification_error_handling.error_log_file }}"
  when:
    - notification_deployment_report.status == "SUCCESS"
    - not notification_deployment_config.debug_mode | bool
  ignore_errors: yes
  tags:
    - notification
    - cleanup

- name: "Notification | Message de finalisation"
  debug:
    msg: |
      {% if notification_deployment_report.status == 'SUCCESS' %}
      🎉 Déploiement du service de notification terminé avec succès !

      📋 Informations de connexion:
      - Hôte: {{ notification_deployment_report.notification_endpoint }}
      - Port: {{ lions_notification_port | default(8080) }}

      📚 Documentation disponible à: https://docs.lions.dev/infrastructure/services/notification
      {% else %}
      💥 Déploiement du service de notification échoué en phase {{ notification_deployment_report.failed_phase }}

      🔍 Consultez les logs d'erreur pour plus de détails:
      - Fichier d'erreur: {{ notification_error_handling.error_log_file }}
      - Rapport JSON: /tmp/notification-deployment-report-{{ notification_deployment_metadata.deployment_id }}.json

      🛠️  Guide de dépannage: https://docs.lions.dev/infrastructure/troubleshooting/notification
      {% endif %}
  tags:
    - notification
    - always
