---
# Titre: Configuration du monitoring pour le service de notification
# Description: Configure le monitoring pour le service de notification avec Prometheus
# Auteur: Équipe LIONS Infrastructure
# Date: 2025-05-08
# Version: 1.0.0

- name: Vérification de l'existence de Prometheus Operator
  k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: servicemonitors.monitoring.coreos.com
  register: prometheus_operator_check
  ignore_errors: yes

- name: Avertissement si Prometheus Operator n'est pas installé
  debug:
    msg: "AVERTISSEMENT: Prometheus Operator n'est pas installé. Le monitoring ne sera pas configuré."
  when: prometheus_operator_check is failed or prometheus_operator_check.resources | length == 0

- name: Déploiement du ServiceMonitor pour le service de notification
  k8s:
    state: present
    src: "{{ temp_dir.path }}/servicemonitor.yml"
  register: servicemonitor_result
  when: prometheus_operator_check is succeeded and prometheus_operator_check.resources | length > 0 and notification_prometheus_scrape | default(true) | bool

- name: Vérification de l'existence du ServiceMonitor
  k8s_info:
    api_version: monitoring.coreos.com/v1
    kind: ServiceMonitor
    namespace: "{{ app_namespace }}"
    name: "{{ app_name }}"
  register: servicemonitor_check
  ignore_errors: yes
  when: prometheus_operator_check is succeeded and prometheus_operator_check.resources | length > 0 and notification_prometheus_scrape | default(true) | bool

- name: Avertissement si le ServiceMonitor n'a pas été créé
  debug:
    msg: "AVERTISSEMENT: Le ServiceMonitor pour le service de notification n'a pas été créé. Vérifiez les logs pour plus d'informations."
  when: prometheus_operator_check is succeeded and prometheus_operator_check.resources | length > 0 and notification_prometheus_scrape | default(true) | bool and (servicemonitor_check is failed or servicemonitor_check.resources | length == 0)

- name: Vérification de l'existence de Grafana
  k8s_info:
    api_version: v1
    kind: Service
    namespace: monitoring
    name: grafana
  register: grafana_check
  ignore_errors: yes

- name: Avertissement si Grafana n'est pas installé
  debug:
    msg: "AVERTISSEMENT: Grafana n'est pas installé. Les dashboards ne seront pas configurés."
  when: grafana_check is failed or grafana_check.resources | length == 0

- name: Création du ConfigMap pour le dashboard du service de notification
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ app_name }}-dashboard"
        namespace: monitoring
        labels:
          app: "{{ app_name }}"
          grafana_dashboard: "1"
      data:
        notification-service-dashboard.json: |
          {
            "annotations": {
              "list": []
            },
            "editable": true,
            "fiscalYearStartMonth": 0,
            "graphTooltip": 0,
            "id": null,
            "links": [],
            "liveNow": false,
            "panels": [
              {
                "datasource": {
                  "type": "prometheus",
                  "uid": "prometheus"
                },
                "fieldConfig": {
                  "defaults": {
                    "color": {
                      "mode": "palette-classic"
                    },
                    "custom": {
                      "axisCenteredZero": false,
                      "axisColorMode": "text",
                      "axisLabel": "",
                      "axisPlacement": "auto",
                      "barAlignment": 0,
                      "drawStyle": "line",
                      "fillOpacity": 10,
                      "gradientMode": "none",
                      "hideFrom": {
                        "legend": false,
                        "tooltip": false,
                        "viz": false
                      },
                      "lineInterpolation": "linear",
                      "lineWidth": 1,
                      "pointSize": 5,
                      "scaleDistribution": {
                        "type": "linear"
                      },
                      "showPoints": "never",
                      "spanNulls": false,
                      "stacking": {
                        "group": "A",
                        "mode": "none"
                      },
                      "thresholdsStyle": {
                        "mode": "off"
                      }
                    },
                    "mappings": [],
                    "thresholds": {
                      "mode": "absolute",
                      "steps": [
                        {
                          "color": "green",
                          "value": null
                        },
                        {
                          "color": "red",
                          "value": 80
                        }
                      ]
                    },
                    "unit": "short"
                  },
                  "overrides": []
                },
                "gridPos": {
                  "h": 8,
                  "w": 12,
                  "x": 0,
                  "y": 0
                },
                "id": 1,
                "options": {
                  "legend": {
                    "calcs": [],
                    "displayMode": "list",
                    "placement": "bottom",
                    "showLegend": true
                  },
                  "tooltip": {
                    "mode": "single",
                    "sort": "none"
                  }
                },
                "targets": [
                  {
                    "datasource": {
                      "type": "prometheus",
                      "uid": "prometheus"
                    },
                    "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\"}[1m])) by (uri)",
                    "refId": "A"
                  }
                ],
                "title": "Requêtes HTTP par URI",
                "type": "timeseries"
              },
              {
                "datasource": {
                  "type": "prometheus",
                  "uid": "prometheus"
                },
                "fieldConfig": {
                  "defaults": {
                    "color": {
                      "mode": "palette-classic"
                    },
                    "custom": {
                      "axisCenteredZero": false,
                      "axisColorMode": "text",
                      "axisLabel": "",
                      "axisPlacement": "auto",
                      "barAlignment": 0,
                      "drawStyle": "line",
                      "fillOpacity": 10,
                      "gradientMode": "none",
                      "hideFrom": {
                        "legend": false,
                        "tooltip": false,
                        "viz": false
                      },
                      "lineInterpolation": "linear",
                      "lineWidth": 1,
                      "pointSize": 5,
                      "scaleDistribution": {
                        "type": "linear"
                      },
                      "showPoints": "never",
                      "spanNulls": false,
                      "stacking": {
                        "group": "A",
                        "mode": "none"
                      },
                      "thresholdsStyle": {
                        "mode": "off"
                      }
                    },
                    "mappings": [],
                    "thresholds": {
                      "mode": "absolute",
                      "steps": [
                        {
                          "color": "green",
                          "value": null
                        },
                        {
                          "color": "red",
                          "value": 80
                        }
                      ]
                    },
                    "unit": "short"
                  },
                  "overrides": []
                },
                "gridPos": {
                  "h": 8,
                  "w": 12,
                  "x": 12,
                  "y": 0
                },
                "id": 2,
                "options": {
                  "legend": {
                    "calcs": [],
                    "displayMode": "list",
                    "placement": "bottom",
                    "showLegend": true
                  },
                  "tooltip": {
                    "mode": "single",
                    "sort": "none"
                  }
                },
                "targets": [
                  {
                    "datasource": {
                      "type": "prometheus",
                      "uid": "prometheus"
                    },
                    "expr": "sum(notification_sent_total{application=\"$application\"}) by (channel)",
                    "refId": "A"
                  }
                ],
                "title": "Notifications envoyées par canal",
                "type": "timeseries"
              }
            ],
            "refresh": "",
            "schemaVersion": 38,
            "style": "dark",
            "tags": ["notification-service"],
            "templating": {
              "list": [
                {
                  "current": {
                    "selected": false,
                    "text": "All",
                    "value": "$__all"
                  },
                  "datasource": {
                    "type": "prometheus",
                    "uid": "prometheus"
                  },
                  "definition": "label_values(application)",
                  "hide": 0,
                  "includeAll": true,
                  "label": "Application",
                  "multi": false,
                  "name": "application",
                  "options": [],
                  "query": {
                    "query": "label_values(application)",
                    "refId": "StandardVariableQuery"
                  },
                  "refresh": 1,
                  "regex": "",
                  "skipUrlSync": false,
                  "sort": 0,
                  "type": "query"
                }
              ]
            },
            "time": {
              "from": "now-6h",
              "to": "now"
            },
            "timepicker": {},
            "timezone": "",
            "title": "Service de Notification",
            "uid": "notification-service-dashboard",
            "version": 1,
            "weekStart": ""
          }
  register: dashboard_result
  ignore_errors: yes
  when: grafana_check is succeeded and grafana_check.resources | length > 0

- name: Avertissement si le dashboard n'a pas été créé
  debug:
    msg: "AVERTISSEMENT: Le dashboard Grafana pour le service de notification n'a pas été créé. Vérifiez les logs pour plus d'informations."
  when: grafana_check is succeeded and grafana_check.resources | length > 0 and dashboard_result is failed

- name: Création des règles d'alerte pour le service de notification
  k8s:
    state: present
    definition:
      apiVersion: monitoring.coreos.com/v1
      kind: PrometheusRule
      metadata:
        name: "{{ app_name }}-alerts"
        namespace: monitoring
        labels:
          app: "{{ app_name }}"
          prometheus: kube-prometheus
          role: alert-rules
      spec:
        groups:
          - name: notification-service.rules
            rules:
              - alert: NotificationServiceDown
                expr: up{job="{{ app_name }}"} == 0
                for: 5m
                labels:
                  severity: critical
                  service: notification
                annotations:
                  summary: "Service de notification indisponible"
                  description: "Le service de notification {{ app_name }} est indisponible depuis 5 minutes."
              
              - alert: NotificationServiceHighErrorRate
                expr: sum(rate(http_server_requests_seconds_count{application="{{ app_name }}",status=~"5.."}[5m])) / sum(rate(http_server_requests_seconds_count{application="{{ app_name }}"}[5m])) > 0.05
                for: 5m
                labels:
                  severity: warning
                  service: notification
                annotations:
                  summary: "Taux d'erreur élevé pour le service de notification"
                  description: "Le service de notification {{ app_name }} a un taux d'erreur supérieur à 5% depuis 5 minutes."
              
              - alert: NotificationDeliveryFailure
                expr: sum(increase(notification_delivery_failure_total{application="{{ app_name }}"}[15m])) > 10
                for: 5m
                labels:
                  severity: warning
                  service: notification
                annotations:
                  summary: "Échecs de livraison de notifications"
                  description: "Le service de notification {{ app_name }} a rencontré plus de 10 échecs de livraison au cours des 15 dernières minutes."
  register: alerts_result
  ignore_errors: yes
  when: prometheus_operator_check is succeeded and prometheus_operator_check.resources | length > 0

- name: Avertissement si les règles d'alerte n'ont pas été créées
  debug:
    msg: "AVERTISSEMENT: Les règles d'alerte pour le service de notification n'ont pas été créées. Vérifiez les logs pour plus d'informations."
  when: prometheus_operator_check is succeeded and prometheus_operator_check.resources | length > 0 and alerts_result is failed