---
# =========================================================================
# LIONS INFRASTRUCTURE 5.0 - NOTIFICATION SERVICE VALIDATION
# =========================================================================
# Description: Validation complète post-déploiement du service de notification
# Version: 5.0.0
# Maintainer: DevOps Team LIONS
# Documentation: https://docs.lions.dev/notification/validation
# =========================================================================

- name: "📊 [NOTIFICATION-VALID] Vérification de l'état des pods"
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ notification_namespace }}"
    label_selectors:
      - "app.kubernetes.io/name={{ notification_service_name }}"
  register: pods_status
  until: pods_status.resources | length > 0 and pods_status.resources | selectattr('status.phase', 'equalto', 'Running') | list | length == pods_status.resources | length
  retries: 20
  delay: 15
  tags: [validation, pods]

- name: "🌍 [NOTIFICATION-VALID] Vérification du Service Kubernetes"
  k8s_info:
    api_version: v1
    kind: Service
    namespace: "{{ notification_namespace }}"
    name: "{{ notification_service_name }}"
  register: service_status
  failed_when: service_status.resources | length == 0
  tags: [validation, service]

- name: "🌐 [NOTIFICATION-VALID] Vérification de l'Ingress"
  k8s_info:
    api_version: networking.k8s.io/v1
    kind: Ingress
    namespace: "{{ notification_namespace }}"
    name: "{{ notification_service_name }}"
  register: ingress_status
  failed_when: false
  when: notification_ingress.enabled | bool
  tags: [validation, ingress]

- name: "🩹 [NOTIFICATION-VALID] Test de santé de l'application"
  uri:
    url: "{{ notification_urls.internal }}{{ notification_endpoints.health }}"
    method: GET
    status_code: 200
    timeout: 30
  register: health_check
  retries: 10
  delay: 10
  until: health_check is succeeded
  tags: [validation, health]

- name: "📊 [NOTIFICATION-VALID] Validation des métriques Prometheus"
  uri:
    url: "{{ notification_urls.internal }}{{ notification_endpoints.metrics }}"
    method: GET
    status_code: 200
    timeout: 30
  register: metrics_check
  when: notification_monitoring.enabled | bool
  ignore_errors: true
  tags: [validation, metrics]

- name: "📬 [NOTIFICATION-VALID] Test des canaux de notification"
  uri:
    url: "{{ notification_urls.internal }}/api/channels/status"
    method: GET
    status_code: [200, 404]  # 404 OK si endpoint pas implémenté
    timeout: 30
  register: channels_check
  ignore_errors: true
  tags: [validation, channels]

- name: "🔍 [NOTIFICATION-VALID] Vérification des logs d'erreurs"
  kubernetes.core.k8s_log:
    namespace: "{{ notification_namespace }}"
    name: "{{ pods_status.resources[0].metadata.name }}"
    tail_lines: 100
  register: pod_logs
  when: pods_status.resources | length > 0
  tags: [validation, logs]

- name: "⚠️  [NOTIFICATION-VALID] Analyse des erreurs dans les logs"
  set_fact:
    error_count: "{{ pod_logs.log.split('\n') | select('match', '.*[Ee]rror.*') | list | length }}"
  when: pod_logs is defined and pod_logs.log is defined
  tags: [validation, logs]

- name: "🌍 [NOTIFICATION-VALID] Test d'accessibilité externe"
  uri:
    url: "{{ notification_urls.external }}{{ notification_endpoints.health }}"
    method: GET
    status_code: 200
    timeout: 30
    validate_certs: false
  register: external_access
  when:
    - notification_ingress.enabled | bool
    - notification_environment != 'development'
  ignore_errors: true
  tags: [validation, external]

- name: "📊 [NOTIFICATION-VALID] Collecte des métriques de validation"
  set_fact:
    notification_validation_metrics:
      pods_running: "{{ pods_status.resources | selectattr('status.phase', 'equalto', 'Running') | list | length }}"
      total_pods: "{{ pods_status.resources | length }}"
      service_available: "{{ service_status.resources | length > 0 }}"
      ingress_configured: "{{ ingress_status.resources | length > 0 if notification_ingress.enabled else false }}"
      health_check_passed: "{{ health_check is succeeded }}"
      metrics_available: "{{ metrics_check is succeeded if notification_monitoring.enabled else 'N/A' }}"
      external_access_ok: "{{ external_access is succeeded if (notification_ingress.enabled and notification_environment != 'development') else 'N/A' }}"
      error_count: "{{ error_count | default(0) }}"
  tags: [validation, metrics]

- name: "📊 [NOTIFICATION-VALID] Rapport de validation complet"
  debug:
    msg:
      - "======================================================"
      - "📊 RAPPORT DE VALIDATION - SERVICE DE NOTIFICATION"
      - "======================================================"
      - "🏷️  Service: {{ notification_service_name }}"
      - "🌐 Namespace: {{ notification_namespace }}"
      - "🌍 Environnement: {{ notification_environment }}"
      - "📆 Version: {{ notification_service_meta.version }}"
      - "======================================================"
      - "📊 ÉTAT DES RESSOURCES:"
      - "  🐋 Pods: {{ notification_validation_metrics.pods_running }}/{{ notification_validation_metrics.total_pods }} en cours d'exécution"
      - "  🌍 Service: {{ '✅ Disponible' if notification_validation_metrics.service_available else '❌ Indisponible' }}"
      - "  🌐 Ingress: {{ '✅ Configuré' if notification_validation_metrics.ingress_configured else ('🚫 Désactivé' if not notification_ingress.enabled else '❌ Échec') }}"
      - "======================================================"
      - "🩹 TESTS FONCTIONNELS:"
      - "  📊 Santé: {{ '✅ OK' if notification_validation_metrics.health_check_passed else '❌ ÉCHEC' }}"
      - "  📈 Métriques: {{ '✅ Disponibles' if notification_validation_metrics.metrics_available == True else ('🚫 Désactivées' if notification_validation_metrics.metrics_available == 'N/A' else '❌ Échec') }}"
      - "  🌍 Accès externe: {{ '✅ OK' if notification_validation_metrics.external_access_ok == True else ('🚫 Non testé' if notification_validation_metrics.external_access_ok == 'N/A' else '❌ Échec') }}"
      - "  📝 Erreurs logs: {{ notification_validation_metrics.error_count }}"
      - "======================================================"
      - "📋 CONFIGURATION:"
      - "  📬 Email: {{ '✅ Activé' if notification_app_config.channels.email.enabled else '🚫 Désactivé' }}"
      - "  💬 Slack: {{ '✅ Activé' if notification_app_config.channels.slack.enabled else '🚫 Désactivé' }}"
      - "  📱 SMS: {{ '✅ Activé' if notification_app_config.channels.sms.enabled else '🚫 Désactivé' }}"
      - "  📈 Monitoring: {{ '✅ Activé' if notification_monitoring.enabled else '🚫 Désactivé' }}"
      - "======================================================"
      - "🔗 URLs D'ACCÈS:"
      - "  Interne: {{ notification_urls.internal }}"
      - "  Externe: {{ notification_urls.external if notification_ingress.enabled else 'Non configuré' }}"
      - "======================================================"
      - "🏁 STATUT FINAL: {{ '✅ SUCCÈS' if (notification_validation_metrics.health_check_passed and notification_validation_metrics.service_available and notification_validation_metrics.pods_running > 0) else '❌ ÉCHEC' }}"
      - "======================================================"
  tags: [validation, summary]

- name: "❌ [NOTIFICATION-VALID] Échec si validation critique"
  fail:
    msg: "La validation du service de notification a échoué. Vérifiez les logs pour plus d'informations."
  when:
    - not notification_validation_metrics.health_check_passed
    - not notification_validation_metrics.service_available
    - notification_validation_metrics.pods_running == 0
  tags: [validation, failure]