---
# Titre: Tâches pour le déploiement d'applications PrimeReact
# Description: Déploie une application PrimeReact sur Kubernetes
# Auteur: Équipe LIONS Infrastructure
# Date: 2025-05-07
# Version: 1.0.0

- name: Vérification des prérequis pour PrimeReact
  include_tasks: prerequisites.yml

- name: Préparation des ressources Kubernetes
  include_tasks: prepare.yml

- name: Déploiement de l'application PrimeReact
  include_tasks: deploy.yml

- name: Configuration du monitoring pour PrimeReact
  include_tasks: monitoring.yml

- name: Validation post-déploiement
  include_tasks: validate.yml