---
# Titre: Préparation des ressources pour PrimeReact
# Description: Prépare les ressources nécessaires pour déployer une application PrimeReact
# Auteur: Équipe LIONS Infrastructure
# Date: 2025-05-07
# Version: 1.0.0

- name: Création du répertoire temporaire pour les templates
  tempfile:
    state: directory
    suffix: primereact-deploy
  register: temp_dir
  changed_when: false

- name: Génération des fichiers de configuration Kubernetes
  template:
    src: "{{ item.src }}"
    dest: "{{ temp_dir.path }}/{{ item.dest }}"
  loop:
    - { src: "deployment.yml.j2", dest: "deployment.yml" }
    - { src: "service.yml.j2", dest: "service.yml" }
    - { src: "ingress.yml.j2", dest: "ingress.yml" }
    - { src: "configmap.yml.j2", dest: "configmap.yml" }
    - { src: "serviceaccount.yml.j2", dest: "serviceaccount.yml" }
    - { src: "servicemonitor.yml.j2", dest: "servicemonitor.yml" }
    - { src: "networkpolicy.yml.j2", dest: "networkpolicy.yml" }
  register: templates_generated

- name: Vérification des fichiers générés
  stat:
    path: "{{ temp_dir.path }}/{{ item }}"
  loop:
    - "deployment.yml"
    - "service.yml"
    - "ingress.yml"
    - "configmap.yml"
    - "serviceaccount.yml"
    - "servicemonitor.yml"
    - "networkpolicy.yml"
  register: files_check
  failed_when: not item.stat.exists

- name: Création du compte de service
  k8s:
    state: present
    src: "{{ temp_dir.path }}/serviceaccount.yml"
  register: serviceaccount_result

- name: Création du ConfigMap pour la configuration de l'application
  k8s:
    state: present
    src: "{{ temp_dir.path }}/configmap.yml"
  register: configmap_result

- name: Création de la NetworkPolicy pour l'application
  k8s:
    state: present
    src: "{{ temp_dir.path }}/networkpolicy.yml"
  register: networkpolicy_result
  when: primereact_create_networkpolicy | bool

- name: Vérification de l'existence des secrets nécessaires
  k8s_info:
    api_version: v1
    kind: Secret
    namespace: "{{ app_namespace }}"
    name: "{{ app_name }}-secrets"
  register: secrets_info
  ignore_errors: yes

- name: Avertissement si les secrets n'existent pas
  debug:
    msg: "AVERTISSEMENT: Les secrets pour l'application {{ app_name }} n'existent pas. Utilisez kubectl pour créer les secrets nécessaires."
  when: secrets_info is failed or secrets_info.resources | length == 0

- name: Préparation des ressources spécifiques à PrimeReact
  debug:
    msg: "Préparation des ressources spécifiques à PrimeReact"

- name: Vérification de l'existence du service de cache Redis
  k8s_info:
    api_version: v1
    kind: Service
    namespace: "{{ app_namespace }}"
    name: "{{ primereact_redis_service | default(app_name + '-redis') }}"
  register: redis_service_info
  ignore_errors: yes
  when: primereact_use_redis | bool

- name: Avertissement si le service Redis n'existe pas
  debug:
    msg: "AVERTISSEMENT: Le service Redis n'existe pas. L'application PrimeReact pourrait avoir des performances réduites."
  when: primereact_use_redis | bool and (redis_service_info is failed or redis_service_info.resources | length == 0)