---
# =========================================================================
# LIONS INFRASTRUCTURE 5.0 - RÔLE POSTGRESQL
# =========================================================================
# Description: Orchestrateur principal pour le déploiement PostgreSQL
# Version: 5.0.0
# Maintainer: DevOps Team <devops@lions.dev>
# Documentation: https://docs.lions.dev/infrastructure/database/postgresql
# =========================================================================

# =========================================================================
# MÉTADONNÉES ET CONFIGURATION
# =========================================================================
- name: "PostgreSQL | Initialisation des métadonnées de déploiement"
  set_fact:
    postgres_deployment_metadata:
      role_name: "postgresql"
      role_version: "5.0.0"
      deployment_id: "{{ ansible_date_time.epoch }}"
      environment: "{{ lions_environment | default('development') }}"
      namespace: "{{ lions_postgres_namespace | default('database') }}"
      started_at: "{{ ansible_date_time.iso8601 }}"
      started_by: "{{ ansible_user_id | default('system') }}"
    postgres_deployment_config:
      dry_run: "{{ lions_dry_run | default(false) | bool }}"
      debug_mode: "{{ lions_debug_mode | default(false) | bool }}"
      skip_validation: "{{ postgres_skip_validation | default(false) | bool }}"
      force_recreate: "{{ postgres_force_recreate | default(false) | bool }}"
  tags:
    - postgres
    - metadata
    - always

- name: "PostgreSQL | Affichage des informations de déploiement"
  debug:
    msg:
      - "🚀 Démarrage du déploiement PostgreSQL"
      - "📊 Environnement: {{ postgres_deployment_metadata.environment }}"
      - "🏷️  Namespace: {{ postgres_deployment_metadata.namespace }}"
      - "🆔 ID de déploiement: {{ postgres_deployment_metadata.deployment_id }}"
      - "⏰ Démarré le: {{ postgres_deployment_metadata.started_at }}"
      - "👤 Initié par: {{ postgres_deployment_metadata.started_by }}"
      - "🔧 Mode debug: {{ postgres_deployment_config.debug_mode }}"
      - "🧪 Dry run: {{ postgres_deployment_config.dry_run }}"
  when: postgres_deployment_config.debug_mode | bool
  tags:
    - postgres
    - debug
    - always

# =========================================================================
# GESTION DES ERREURS ET ROLLBACK
# =========================================================================
- name: "PostgreSQL | Configuration de la gestion d'erreurs"
  set_fact:
    postgres_error_handling:
      max_retries: "{{ postgres_max_retries | default(3) }}"
      retry_delay: "{{ postgres_retry_delay | default(10) }}"
      rollback_on_failure: "{{ postgres_rollback_on_failure | default(true) | bool }}"
      error_log_file: "/tmp/postgres-deployment-{{ postgres_deployment_metadata.deployment_id }}.log"
  tags:
    - postgres
    - error-handling
    - always

# =========================================================================
# VÉRIFICATIONS PRÉALABLES CRITIQUES
# =========================================================================
- name: "PostgreSQL | Vérification de l'état de l'environnement"
  block:
    - name: "PostgreSQL | Vérification de l'accessibilité du cluster Kubernetes"
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Namespace
        name: "{{ postgres_deployment_metadata.namespace }}"
      register: postgres_namespace_check
      failed_when: false

    - name: "PostgreSQL | Vérification des variables d'environnement critiques"
      assert:
        that:
          - lions_postgres_enabled is defined
          - lions_postgres_enabled | bool
          - lions_postgres_version is defined
          - lions_postgres_version | length > 0
          - postgres_deployment_metadata.namespace is defined
        fail_msg: "Variables d'environnement PostgreSQL manquantes ou incorrectes"
        success_msg: "Variables d'environnement PostgreSQL validées"

  rescue:
    - name: "PostgreSQL | Gestion d'erreur - Vérifications préalables"
      fail:
        msg: "❌ Échec des vérifications préalables PostgreSQL: {{ ansible_failed_result.msg | default('Erreur inconnue') }}"

  tags:
    - postgres
    - preflight
    - validation

# =========================================================================
# PHASE 1: PRÉREQUIS ET DÉPENDANCES
# =========================================================================
- name: "PostgreSQL | Phase 1 - Vérification des prérequis"
  block:
    - name: "PostgreSQL | Inclusion des tâches de prérequis"
      include_tasks: prerequisites.yml
      vars:
        current_phase: "prerequisites"
        phase_description: "Vérification des prérequis système et Kubernetes"

  rescue:
    - name: "PostgreSQL | Échec Phase 1 - Prérequis"
      set_fact:
        postgres_deployment_failed: true
        postgres_failure_phase: "prerequisites"
        postgres_failure_reason: "{{ ansible_failed_result.msg | default('Échec des prérequis') }}"

    - name: "PostgreSQL | Log d'erreur Phase 1"
      lineinfile:
        path: "{{ postgres_error_handling.error_log_file }}"
        line: "[{{ ansible_date_time.iso8601 }}] ERREUR Phase 1 (Prérequis): {{ postgres_failure_reason }}"
        create: yes

    - name: "PostgreSQL | Arrêt du déploiement - Phase 1"
      fail:
        msg: "❌ Déploiement PostgreSQL interrompu en Phase 1 (Prérequis): {{ postgres_failure_reason }}"

  tags:
    - postgres
    - prerequisites
    - phase-1

# =========================================================================
# PHASE 2: PRÉPARATION DES RESSOURCES
# =========================================================================
- name: "PostgreSQL | Phase 2 - Préparation des ressources"
  block:
    - name: "PostgreSQL | Inclusion des tâches de préparation"
      include_tasks: prepare.yml
      vars:
        current_phase: "preparation"
        phase_description: "Création des ressources Kubernetes de base"

  rescue:
    - name: "PostgreSQL | Échec Phase 2 - Préparation"
      set_fact:
        postgres_deployment_failed: true
        postgres_failure_phase: "preparation"
        postgres_failure_reason: "{{ ansible_failed_result.msg | default('Échec de la préparation') }}"

    - name: "PostgreSQL | Log d'erreur Phase 2"
      lineinfile:
        path: "{{ postgres_error_handling.error_log_file }}"
        line: "[{{ ansible_date_time.iso8601 }}] ERREUR Phase 2 (Préparation): {{ postgres_failure_reason }}"
        create: yes

    - name: "PostgreSQL | Nettoyage partiel après échec Phase 2"
      include_tasks: cleanup.yml
      vars:
        cleanup_scope: "preparation"
      when: postgres_error_handling.rollback_on_failure | bool

    - name: "PostgreSQL | Arrêt du déploiement - Phase 2"
      fail:
        msg: "❌ Déploiement PostgreSQL interrompu en Phase 2 (Préparation): {{ postgres_failure_reason }}"

  when: postgres_deployment_failed is not defined
  tags:
    - postgres
    - preparation
    - phase-2

# =========================================================================
# PHASE 3: DÉPLOIEMENT PRINCIPAL
# =========================================================================
- name: "PostgreSQL | Phase 3 - Déploiement principal"
  block:
    - name: "PostgreSQL | Inclusion des tâches de déploiement"
      include_tasks: deploy.yml
      vars:
        current_phase: "deployment"
        phase_description: "Déploiement des composants PostgreSQL"

  rescue:
    - name: "PostgreSQL | Échec Phase 3 - Déploiement"
      set_fact:
        postgres_deployment_failed: true
        postgres_failure_phase: "deployment"
        postgres_failure_reason: "{{ ansible_failed_result.msg | default('Échec du déploiement') }}"

    - name: "PostgreSQL | Log d'erreur Phase 3"
      lineinfile:
        path: "{{ postgres_error_handling.error_log_file }}"
        line: "[{{ ansible_date_time.iso8601 }}] ERREUR Phase 3 (Déploiement): {{ postgres_failure_reason }}"
        create: yes

    - name: "PostgreSQL | Rollback complet après échec Phase 3"
      include_tasks: rollback.yml
      vars:
        rollback_reason: "Échec du déploiement principal"
      when: postgres_error_handling.rollback_on_failure | bool

    - name: "PostgreSQL | Arrêt du déploiement - Phase 3"
      fail:
        msg: "❌ Déploiement PostgreSQL interrompu en Phase 3 (Déploiement): {{ postgres_failure_reason }}"

  when: postgres_deployment_failed is not defined
  tags:
    - postgres
    - deployment
    - phase-3

# =========================================================================
# PHASE 4: CONFIGURATION DU MONITORING
# =========================================================================
- name: "PostgreSQL | Phase 4 - Configuration du monitoring"
  block:
    - name: "PostgreSQL | Inclusion des tâches de monitoring"
      include_tasks: monitoring.yml
      vars:
        current_phase: "monitoring"
        phase_description: "Configuration des métriques et alertes PostgreSQL"

  rescue:
    - name: "PostgreSQL | Avertissement Phase 4 - Monitoring"
      debug:
        msg:
          - "⚠️  Échec de la configuration du monitoring PostgreSQL"
          - "ℹ️  Le déploiement principal a réussi, mais les métriques peuvent être indisponibles"
          - "🔍 Erreur: {{ ansible_failed_result.msg | default('Erreur de monitoring inconnue') }}"

    - name: "PostgreSQL | Log d'avertissement Phase 4"
      lineinfile:
        path: "{{ postgres_error_handling.error_log_file }}"
        line: "[{{ ansible_date_time.iso8601 }}] AVERTISSEMENT Phase 4 (Monitoring): {{ ansible_failed_result.msg | default('Erreur de monitoring') }}"
        create: yes

    - name: "PostgreSQL | Marquage du monitoring comme défaillant"
      set_fact:
        postgres_monitoring_failed: true

  when:
    - postgres_deployment_failed is not defined
    - lions_monitoring_enabled | default(true) | bool
  tags:
    - postgres
    - monitoring
    - phase-4

# =========================================================================
# PHASE 5: VALIDATION POST-DÉPLOIEMENT
# =========================================================================
- name: "PostgreSQL | Phase 5 - Validation post-déploiement"
  block:
    - name: "PostgreSQL | Inclusion des tâches de validation"
      include_tasks: validate.yml
      vars:
        current_phase: "validation"
        phase_description: "Validation de l'état et des fonctionnalités PostgreSQL"

  rescue:
    - name: "PostgreSQL | Échec Phase 5 - Validation"
      set_fact:
        postgres_deployment_failed: true
        postgres_failure_phase: "validation"
        postgres_failure_reason: "{{ ansible_failed_result.msg | default('Échec de la validation') }}"

    - name: "PostgreSQL | Log d'erreur Phase 5"
      lineinfile:
        path: "{{ postgres_error_handling.error_log_file }}"
        line: "[{{ ansible_date_time.iso8601 }}] ERREUR Phase 5 (Validation): {{ postgres_failure_reason }}"
        create: yes

    - name: "PostgreSQL | Décision sur le rollback après validation"
      debug:
        msg: "⚠️  Validation échouée mais PostgreSQL peut être partiellement fonctionnel"

    - name: "PostgreSQL | Arrêt avec avertissement - Phase 5"
      fail:
        msg: "⚠️  Déploiement PostgreSQL terminé avec des erreurs de validation: {{ postgres_failure_reason }}"

  when:
    - postgres_deployment_failed is not defined
    - not postgres_deployment_config.skip_validation | bool
  tags:
    - postgres
    - validation
    - phase-5

# =========================================================================
# PHASE 6: CONFIGURATION DE LA SAUVEGARDE
# =========================================================================
- name: "PostgreSQL | Phase 6 - Configuration de la sauvegarde"
  block:
    - name: "PostgreSQL | Inclusion des tâches de sauvegarde"
      include_tasks: backup.yml
      vars:
        current_phase: "backup"
        phase_description: "Configuration des stratégies de sauvegarde PostgreSQL"

  rescue:
    - name: "PostgreSQL | Avertissement Phase 6 - Sauvegarde"
      debug:
        msg:
          - "⚠️  Échec de la configuration de sauvegarde PostgreSQL"
          - "ℹ️  PostgreSQL fonctionne mais les sauvegardes automatiques sont désactivées"
          - "🔍 Erreur: {{ ansible_failed_result.msg | default('Erreur de sauvegarde inconnue') }}"

    - name: "PostgreSQL | Log d'avertissement Phase 6"
      lineinfile:
        path: "{{ postgres_error_handling.error_log_file }}"
        line: "[{{ ansible_date_time.iso8601 }}] AVERTISSEMENT Phase 6 (Sauvegarde): {{ ansible_failed_result.msg | default('Erreur de sauvegarde') }}"
        create: yes

    - name: "PostgreSQL | Marquage de la sauvegarde comme défaillante"
      set_fact:
        postgres_backup_failed: true

  when:
    - postgres_deployment_failed is not defined
    - lions_backup_enabled | default(true) | bool
    - lions_postgres_backup_enabled | default(true) | bool
  tags:
    - postgres
    - backup
    - phase-6

# =========================================================================
# FINALISATION ET RAPPORT DE DÉPLOIEMENT
# =========================================================================
- name: "PostgreSQL | Génération du rapport de déploiement"
  set_fact:
    postgres_deployment_report:
      status: "{{ 'FAILED' if postgres_deployment_failed | default(false) else 'SUCCESS' }}"
      environment: "{{ postgres_deployment_metadata.environment }}"
      namespace: "{{ postgres_deployment_metadata.namespace }}"
      deployment_id: "{{ postgres_deployment_metadata.deployment_id }}"
      started_at: "{{ postgres_deployment_metadata.started_at }}"
      completed_at: "{{ ansible_date_time.iso8601 }}"
      duration: "{{ (ansible_date_time.epoch | int) - (postgres_deployment_metadata.deployment_id | int) }}"
      failed_phase: "{{ postgres_failure_phase | default('N/A') }}"
      failure_reason: "{{ postgres_failure_reason | default('N/A') }}"
      monitoring_status: "{{ 'FAILED' if postgres_monitoring_failed | default(false) else 'OK' }}"
      backup_status: "{{ 'FAILED' if postgres_backup_failed | default(false) else 'OK' }}"
      postgres_version: "{{ lions_postgres_version }}"
      postgres_service_name: "{{ lions_postgres_service_name }}"
      postgres_endpoint: "{{ lions_postgres_service_name }}.{{ postgres_deployment_metadata.namespace }}.svc.cluster.local:{{ lions_postgres_port }}"
  tags:
    - postgres
    - report
    - always

- name: "PostgreSQL | Affichage du rapport de déploiement"
  debug:
    msg:
      - "=============================================="
      - "📊 RAPPORT DE DÉPLOIEMENT POSTGRESQL"
      - "=============================================="
      - "📈 Statut: {{ postgres_deployment_report.status }}"
      - "🌍 Environnement: {{ postgres_deployment_report.environment }}"
      - "🏷️  Namespace: {{ postgres_deployment_report.namespace }}"
      - "🆔 ID de déploiement: {{ postgres_deployment_report.deployment_id }}"
      - "⏰ Durée: {{ postgres_deployment_report.duration }}s"
      - "🐘 Version PostgreSQL: {{ postgres_deployment_report.postgres_version }}"
      - "🔗 Point de connexion: {{ postgres_deployment_report.postgres_endpoint }}"
      - "📊 Monitoring: {{ postgres_deployment_report.monitoring_status }}"
      - "💾 Sauvegarde: {{ postgres_deployment_report.backup_status }}"
      - "{{ '❌ Phase d\'échec: ' + postgres_deployment_report.failed_phase if postgres_deployment_report.status == 'FAILED' else '✅ Déploiement réussi' }}"
      - "{{ '🔍 Raison: ' + postgres_deployment_report.failure_reason if postgres_deployment_report.status == 'FAILED' else '' }}"
      - "=============================================="
  tags:
    - postgres
    - report
    - always

- name: "PostgreSQL | Sauvegarde du rapport de déploiement"
  copy:
    content: "{{ postgres_deployment_report | to_nice_json }}"
    dest: "/tmp/postgres-deployment-report-{{ postgres_deployment_metadata.deployment_id }}.json"
  delegate_to: localhost
  tags:
    - postgres
    - report

# =========================================================================
# NETTOYAGE ET FINALISATION
# =========================================================================
- name: "PostgreSQL | Nettoyage des fichiers temporaires"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ postgres_error_handling.error_log_file }}"
  when:
    - postgres_deployment_report.status == "SUCCESS"
    - not postgres_deployment_config.debug_mode | bool
  ignore_errors: yes
  tags:
    - postgres
    - cleanup

- name: "PostgreSQL | Message de finalisation"
  debug:
    msg: |
      {% if postgres_deployment_report.status == 'SUCCESS' %}
      🎉 Déploiement PostgreSQL terminé avec succès !
      
      📋 Informations de connexion:
      - Hôte: {{ postgres_deployment_report.postgres_endpoint }}
      - Port: {{ lions_postgres_port }}
      - Base de données: {{ lions_postgres_database }}
      
      📚 Documentation disponible à: https://docs.lions.dev/infrastructure/database/postgresql
      {% else %}
      💥 Déploiement PostgreSQL échoué en phase {{ postgres_deployment_report.failed_phase }}
      
      🔍 Consultez les logs d'erreur pour plus de détails:
      - Fichier d'erreur: {{ postgres_error_handling.error_log_file }}
      - Rapport JSON: /tmp/postgres-deployment-report-{{ postgres_deployment_metadata.deployment_id }}.json
      
      🛠️  Guide de dépannage: https://docs.lions.dev/infrastructure/troubleshooting/postgresql
      {% endif %}
  tags:
    - postgres
    - always